# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GenericTelemetryDialog.ui'
#
# Created: Thu Jun 25 09:52:44 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GenericTelemetryDialog(object):
    def setupUi(self, GenericTelemetryDialog):
        GenericTelemetryDialog.setObjectName(_fromUtf8("GenericTelemetryDialog"))
        GenericTelemetryDialog.setWindowModality(QtCore.Qt.NonModal)
        GenericTelemetryDialog.resize(750, 434)
        font = QtGui.QFont()
        font.setPointSize(13)
        GenericTelemetryDialog.setFont(font)
        self.verticalLayout_8 = QtGui.QVBoxLayout(GenericTelemetryDialog)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.subSystemTelemetryPageLabel = QtGui.QLabel(GenericTelemetryDialog)
        self.subSystemTelemetryPageLabel.setObjectName(_fromUtf8("subSystemTelemetryPageLabel"))
        self.verticalLayout.addWidget(self.subSystemTelemetryPageLabel)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.subSystemTextBrowser = QtGui.QTextBrowser(GenericTelemetryDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subSystemTextBrowser.sizePolicy().hasHeightForWidth())
        self.subSystemTextBrowser.setSizePolicy(sizePolicy)
        self.subSystemTextBrowser.setMinimumSize(QtCore.QSize(141, 31))
        self.subSystemTextBrowser.setMaximumSize(QtCore.QSize(141, 31))
        self.subSystemTextBrowser.setObjectName(_fromUtf8("subSystemTextBrowser"))
        self.horizontalLayout.addWidget(self.subSystemTextBrowser)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.packetIdLabel = QtGui.QLabel(GenericTelemetryDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.packetIdLabel.sizePolicy().hasHeightForWidth())
        self.packetIdLabel.setSizePolicy(sizePolicy)
        self.packetIdLabel.setMinimumSize(QtCore.QSize(0, 13))
        self.packetIdLabel.setMaximumSize(QtCore.QSize(16777215, 13))
        self.packetIdLabel.setObjectName(_fromUtf8("packetIdLabel"))
        self.verticalLayout_2.addWidget(self.packetIdLabel)
        self.packetId = QtGui.QLCDNumber(GenericTelemetryDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.packetId.sizePolicy().hasHeightForWidth())
        self.packetId.setSizePolicy(sizePolicy)
        self.packetId.setObjectName(_fromUtf8("packetId"))
        self.verticalLayout_2.addWidget(self.packetId)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_5 = QtGui.QLabel(GenericTelemetryDialog)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_3.addWidget(self.label_5)
        self.sequenceCount = QtGui.QTextBrowser(GenericTelemetryDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequenceCount.sizePolicy().hasHeightForWidth())
        self.sequenceCount.setSizePolicy(sizePolicy)
        self.sequenceCount.setMinimumSize(QtCore.QSize(101, 31))
        self.sequenceCount.setMaximumSize(QtCore.QSize(101, 31))
        self.sequenceCount.setObjectName(_fromUtf8("sequenceCount"))
        self.verticalLayout_3.addWidget(self.sequenceCount)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        spacerItem2 = QtGui.QSpacerItem(146, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.buttonBox = QtGui.QDialogButtonBox(GenericTelemetryDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtGui.QLabel(GenericTelemetryDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(161, 17))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.label_2 = QtGui.QLabel(GenericTelemetryDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(151, 0))
        self.label_2.setMaximumSize(QtCore.QSize(151, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.line_2 = QtGui.QFrame(GenericTelemetryDialog)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_4.addWidget(self.line_2)
        self.label_4 = QtGui.QLabel(GenericTelemetryDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(161, 17))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.label_3 = QtGui.QLabel(GenericTelemetryDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(151, 0))
        self.label_3.setMaximumSize(QtCore.QSize(151, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem3 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.scrollArea = QtGui.QScrollArea(GenericTelemetryDialog)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 709, 1000))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 1000))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.itemLabelTextBrowser_1 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_1.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_1.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_1.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_1.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_1.setObjectName(_fromUtf8("itemLabelTextBrowser_1"))
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_1)
        self.itemLabelTextBrowser_2 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_2.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_2.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_2.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_2.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_2.setObjectName(_fromUtf8("itemLabelTextBrowser_2"))
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_2)
        self.itemLabelTextBrowser_3 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_3.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_3.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_3.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_3.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_3.setObjectName(_fromUtf8("itemLabelTextBrowser_3"))
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_3)
        self.itemLabelTextBrowser_4 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_4.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_4.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_4.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_4.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_4.setObjectName(_fromUtf8("itemLabelTextBrowser_4"))
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_4)
        self.itemLabelTextBrowser_5 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_5.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_5.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_5.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_5.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_5.setObjectName(_fromUtf8("itemLabelTextBrowser_5"))
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_5)
        self.itemLabelTextBrowser_6 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_6.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_6.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_6.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_6.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_6.setObjectName(_fromUtf8("itemLabelTextBrowser_6"))
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_6)
        self.itemLabelTextBrowser_7 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_7.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_7.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_7.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_7.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_7.setObjectName(_fromUtf8("itemLabelTextBrowser_7"))
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_7)
        self.itemLabelTextBrowser_8 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_8.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_8.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_8.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_8.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_8.setObjectName(_fromUtf8("itemLabelTextBrowser_8"))
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_8)
        self.itemLabelTextBrowser_9 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_9.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_9.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_9.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_9.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_9.setObjectName(_fromUtf8("itemLabelTextBrowser_9"))
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_9)
        self.itemLabelTextBrowser_10 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_10.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_10.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_10.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_10.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_10.setObjectName(_fromUtf8("itemLabelTextBrowser_10"))
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_10)
        self.itemLabelTextBrowser_11 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_11.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_11.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_11.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_11.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_11.setObjectName(_fromUtf8("itemLabelTextBrowser_11"))
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_11)
        self.itemLabelTextBrowser_12 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_12.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_12.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_12.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_12.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_12.setObjectName(_fromUtf8("itemLabelTextBrowser_12"))
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_12)
        self.itemLabelTextBrowser_13 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_13.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_13.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_13.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_13.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_13.setObjectName(_fromUtf8("itemLabelTextBrowser_13"))
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_13)
        self.itemLabelTextBrowser_14 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_14.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_14.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_14.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_14.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_14.setObjectName(_fromUtf8("itemLabelTextBrowser_14"))
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_14)
        self.itemLabelTextBrowser_15 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_15.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_15.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_15.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_15.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_15.setObjectName(_fromUtf8("itemLabelTextBrowser_15"))
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_15)
        self.itemLabelTextBrowser_16 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_16.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_16.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_16.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_16.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_16.setObjectName(_fromUtf8("itemLabelTextBrowser_16"))
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_16)
        self.itemLabelTextBrowser_17 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_17.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_17.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_17.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_17.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_17.setObjectName(_fromUtf8("itemLabelTextBrowser_17"))
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_17)
        self.itemLabelTextBrowser_18 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_18.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_18.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_18.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_18.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_18.setObjectName(_fromUtf8("itemLabelTextBrowser_18"))
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_18)
        self.itemLabelTextBrowser_19 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_19.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_19.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_19.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_19.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_19.setObjectName(_fromUtf8("itemLabelTextBrowser_19"))
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_19)
        self.itemLabelTextBrowser_20 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_20.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_20.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_20.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_20.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_20.setObjectName(_fromUtf8("itemLabelTextBrowser_20"))
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_20)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.itemValueTextBrowser_1 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_1.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_1.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_1.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_1.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_1.setObjectName(_fromUtf8("itemValueTextBrowser_1"))
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_1)
        self.itemValueTextBrowser_2 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_2.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_2.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_2.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_2.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_2.setObjectName(_fromUtf8("itemValueTextBrowser_2"))
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_2)
        self.itemValueTextBrowser_3 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_3.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_3.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_3.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_3.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_3.setObjectName(_fromUtf8("itemValueTextBrowser_3"))
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_3)
        self.itemValueTextBrowser_4 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_4.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_4.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_4.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_4.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_4.setObjectName(_fromUtf8("itemValueTextBrowser_4"))
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_4)
        self.itemValueTextBrowser_5 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_5.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_5.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_5.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_5.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_5.setObjectName(_fromUtf8("itemValueTextBrowser_5"))
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_5)
        self.itemValueTextBrowser_6 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_6.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_6.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_6.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_6.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_6.setObjectName(_fromUtf8("itemValueTextBrowser_6"))
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_6)
        self.itemValueTextBrowser_7 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_7.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_7.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_7.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_7.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_7.setObjectName(_fromUtf8("itemValueTextBrowser_7"))
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_7)
        self.itemValueTextBrowser_8 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_8.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_8.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_8.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_8.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_8.setObjectName(_fromUtf8("itemValueTextBrowser_8"))
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_8)
        self.itemValueTextBrowser_9 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_9.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_9.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_9.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_9.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_9.setObjectName(_fromUtf8("itemValueTextBrowser_9"))
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_9)
        self.itemValueTextBrowser_10 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_10.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_10.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_10.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_10.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_10.setObjectName(_fromUtf8("itemValueTextBrowser_10"))
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_10)
        self.itemValueTextBrowser_11 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_11.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_11.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_11.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_11.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_11.setObjectName(_fromUtf8("itemValueTextBrowser_11"))
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_11)
        self.itemValueTextBrowser_12 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_12.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_12.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_12.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_12.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_12.setObjectName(_fromUtf8("itemValueTextBrowser_12"))
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_12)
        self.itemValueTextBrowser_13 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_13.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_13.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_13.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_13.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_13.setObjectName(_fromUtf8("itemValueTextBrowser_13"))
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_13)
        self.itemValueTextBrowser_14 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_14.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_14.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_14.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_14.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_14.setObjectName(_fromUtf8("itemValueTextBrowser_14"))
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_14)
        self.itemValueTextBrowser_15 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_15.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_15.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_15.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_15.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_15.setObjectName(_fromUtf8("itemValueTextBrowser_15"))
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_15)
        self.itemValueTextBrowser_16 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_16.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_16.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_16.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_16.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_16.setObjectName(_fromUtf8("itemValueTextBrowser_16"))
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_16)
        self.itemValueTextBrowser_17 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_17.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_17.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_17.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_17.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_17.setObjectName(_fromUtf8("itemValueTextBrowser_17"))
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_17)
        self.itemValueTextBrowser_18 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_18.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_18.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_18.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_18.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_18.setObjectName(_fromUtf8("itemValueTextBrowser_18"))
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_18)
        self.itemValueTextBrowser_19 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_19.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_19.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_19.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_19.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_19.setObjectName(_fromUtf8("itemValueTextBrowser_19"))
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_19)
        self.itemValueTextBrowser_20 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_20.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_20.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_20.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_20.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_20.setObjectName(_fromUtf8("itemValueTextBrowser_20"))
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_20)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.line = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_3.addWidget(self.line)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.itemLabelTextBrowser_21 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_21.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_21.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_21.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_21.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_21.setObjectName(_fromUtf8("itemLabelTextBrowser_21"))
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_21)
        self.itemLabelTextBrowser_22 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_22.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_22.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_22.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_22.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_22.setObjectName(_fromUtf8("itemLabelTextBrowser_22"))
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_22)
        self.itemLabelTextBrowser_23 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_23.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_23.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_23.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_23.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_23.setObjectName(_fromUtf8("itemLabelTextBrowser_23"))
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_23)
        self.itemLabelTextBrowser_24 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_24.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_24.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_24.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_24.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_24.setObjectName(_fromUtf8("itemLabelTextBrowser_24"))
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_24)
        self.itemLabelTextBrowser_25 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_25.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_25.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_25.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_25.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_25.setObjectName(_fromUtf8("itemLabelTextBrowser_25"))
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_25)
        self.itemLabelTextBrowser_26 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_26.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_26.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_26.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_26.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_26.setObjectName(_fromUtf8("itemLabelTextBrowser_26"))
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_26)
        self.itemLabelTextBrowser_27 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_27.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_27.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_27.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_27.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_27.setObjectName(_fromUtf8("itemLabelTextBrowser_27"))
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_27)
        self.itemLabelTextBrowser_28 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_28.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_28.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_28.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_28.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_28.setObjectName(_fromUtf8("itemLabelTextBrowser_28"))
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_28)
        self.itemLabelTextBrowser_29 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_29.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_29.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_29.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_29.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_29.setObjectName(_fromUtf8("itemLabelTextBrowser_29"))
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_29)
        self.itemLabelTextBrowser_30 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_30.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_30.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_30.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_30.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_30.setObjectName(_fromUtf8("itemLabelTextBrowser_30"))
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_30)
        self.itemLabelTextBrowser_31 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_31.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_31.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_31.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_31.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_31.setObjectName(_fromUtf8("itemLabelTextBrowser_31"))
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_31)
        self.itemLabelTextBrowser_32 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_32.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_32.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_32.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_32.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_32.setObjectName(_fromUtf8("itemLabelTextBrowser_32"))
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_32)
        self.itemLabelTextBrowser_33 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_33.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_33.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_33.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_33.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_33.setObjectName(_fromUtf8("itemLabelTextBrowser_33"))
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_33)
        self.itemLabelTextBrowser_34 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_34.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_34.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_34.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_34.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_34.setObjectName(_fromUtf8("itemLabelTextBrowser_34"))
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_34)
        self.itemLabelTextBrowser_35 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_35.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_35.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_35.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_35.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_35.setObjectName(_fromUtf8("itemLabelTextBrowser_35"))
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_35)
        self.itemLabelTextBrowser_36 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_36.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_36.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_36.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_36.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_36.setObjectName(_fromUtf8("itemLabelTextBrowser_36"))
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_36)
        self.itemLabelTextBrowser_37 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_37.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_37.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_37.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_37.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_37.setObjectName(_fromUtf8("itemLabelTextBrowser_37"))
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_37)
        self.itemLabelTextBrowser_38 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_38.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_38.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_38.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_38.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_38.setObjectName(_fromUtf8("itemLabelTextBrowser_38"))
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_38)
        self.itemLabelTextBrowser_39 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_39.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_39.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_39.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_39.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_39.setObjectName(_fromUtf8("itemLabelTextBrowser_39"))
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_39)
        self.itemLabelTextBrowser_40 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_40.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_40.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_40.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_40.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_40.setObjectName(_fromUtf8("itemLabelTextBrowser_40"))
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_40)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.itemValueTextBrowser_21 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_21.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_21.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_21.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_21.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_21.setObjectName(_fromUtf8("itemValueTextBrowser_21"))
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_21)
        self.itemValueTextBrowser_22 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_22.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_22.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_22.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_22.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_22.setObjectName(_fromUtf8("itemValueTextBrowser_22"))
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_22)
        self.itemValueTextBrowser_23 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_23.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_23.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_23.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_23.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_23.setObjectName(_fromUtf8("itemValueTextBrowser_23"))
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_23)
        self.itemValueTextBrowser_24 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_24.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_24.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_24.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_24.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_24.setObjectName(_fromUtf8("itemValueTextBrowser_24"))
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_24)
        self.itemValueTextBrowser_25 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_25.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_25.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_25.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_25.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_25.setObjectName(_fromUtf8("itemValueTextBrowser_25"))
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_25)
        self.itemValueTextBrowser_26 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_26.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_26.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_26.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_26.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_26.setObjectName(_fromUtf8("itemValueTextBrowser_26"))
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_26)
        self.itemValueTextBrowser_27 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_27.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_27.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_27.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_27.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_27.setObjectName(_fromUtf8("itemValueTextBrowser_27"))
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_27)
        self.itemValueTextBrowser_28 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_28.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_28.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_28.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_28.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_28.setObjectName(_fromUtf8("itemValueTextBrowser_28"))
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_28)
        self.itemValueTextBrowser_29 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_29.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_29.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_29.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_29.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_29.setObjectName(_fromUtf8("itemValueTextBrowser_29"))
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_29)
        self.itemValueTextBrowser_30 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_30.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_30.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_30.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_30.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_30.setObjectName(_fromUtf8("itemValueTextBrowser_30"))
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_30)
        self.itemValueTextBrowser_31 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_31.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_31.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_31.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_31.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_31.setObjectName(_fromUtf8("itemValueTextBrowser_31"))
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_31)
        self.itemValueTextBrowser_32 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_32.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_32.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_32.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_32.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_32.setObjectName(_fromUtf8("itemValueTextBrowser_32"))
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_32)
        self.itemValueTextBrowser_33 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_33.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_33.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_33.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_33.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_33.setObjectName(_fromUtf8("itemValueTextBrowser_33"))
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_33)
        self.itemValueTextBrowser_34 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_34.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_34.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_34.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_34.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_34.setObjectName(_fromUtf8("itemValueTextBrowser_34"))
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_34)
        self.itemValueTextBrowser_35 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_35.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_35.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_35.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_35.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_35.setObjectName(_fromUtf8("itemValueTextBrowser_35"))
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_35)
        self.itemValueTextBrowser_36 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_36.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_36.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_36.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_36.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_36.setObjectName(_fromUtf8("itemValueTextBrowser_36"))
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_36)
        self.itemValueTextBrowser_37 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_37.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_37.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_37.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_37.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_37.setObjectName(_fromUtf8("itemValueTextBrowser_37"))
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_37)
        self.itemValueTextBrowser_38 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_38.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_38.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_38.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_38.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_38.setObjectName(_fromUtf8("itemValueTextBrowser_38"))
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_38)
        self.itemValueTextBrowser_39 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_39.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_39.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_39.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_39.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_39.setObjectName(_fromUtf8("itemValueTextBrowser_39"))
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_39)
        self.itemValueTextBrowser_40 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_40.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_40.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_40.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_40.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_40.setObjectName(_fromUtf8("itemValueTextBrowser_40"))
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_40)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_8.addWidget(self.scrollArea)
        self.label_6 = QtGui.QLabel(GenericTelemetryDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_8.addWidget(self.label_6)

        self.retranslateUi(GenericTelemetryDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), GenericTelemetryDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), GenericTelemetryDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(GenericTelemetryDialog)

    def retranslateUi(self, GenericTelemetryDialog):
        GenericTelemetryDialog.setWindowTitle(_translate("GenericTelemetryDialog", "Telemetry Page", None))
        self.subSystemTelemetryPageLabel.setText(_translate("GenericTelemetryDialog", "Subsystem Telemetry Page", None))
        self.packetIdLabel.setText(_translate("GenericTelemetryDialog", "Packet ID", None))
        self.label_5.setText(_translate("GenericTelemetryDialog", "Sequence Count", None))
        self.label.setText(_translate("GenericTelemetryDialog", "Telemetry Point Label", None))
        self.label_2.setText(_translate("GenericTelemetryDialog", "Telemetry Point Value", None))
        self.label_4.setText(_translate("GenericTelemetryDialog", "Telemetry Point Label", None))
        self.label_3.setText(_translate("GenericTelemetryDialog", "Telemetry Point Value", None))
        self.label_6.setText(_translate("GenericTelemetryDialog", "*No packets? Remember to select the IP address of your spacecraft in the Main Window.", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    GenericTelemetryDialog = QtGui.QDialog()
    ui = Ui_GenericTelemetryDialog()
    ui.setupUi(GenericTelemetryDialog)
    GenericTelemetryDialog.show()
    sys.exit(app.exec_())

