# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TelemetrySystemDialog.ui'
#
# Created: Wed Mar 25 14:24:26 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TelemetrySystemDialog(object):
    def setupUi(self, TelemetrySystemDialog):
        TelemetrySystemDialog.setObjectName(_fromUtf8("TelemetrySystemDialog"))
        TelemetrySystemDialog.resize(515, 600)
        self.verticalLayout = QtGui.QVBoxLayout(TelemetrySystemDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtGui.QLabel(TelemetrySystemDialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        spacerItem3 = QtGui.QSpacerItem(80, 32, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.label_6 = QtGui.QLabel(TelemetrySystemDialog)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.sequenceCount = QtGui.QTextBrowser(TelemetrySystemDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequenceCount.sizePolicy().hasHeightForWidth())
        self.sequenceCount.setSizePolicy(sizePolicy)
        self.sequenceCount.setMinimumSize(QtCore.QSize(130, 30))
        self.sequenceCount.setMaximumSize(QtCore.QSize(130, 30))
        self.sequenceCount.setObjectName(_fromUtf8("sequenceCount"))
        self.horizontalLayout_2.addWidget(self.sequenceCount)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.buttonBox = QtGui.QDialogButtonBox(TelemetrySystemDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_3.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.label_2 = QtGui.QLabel(TelemetrySystemDialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.scrollArea = QtGui.QScrollArea(TelemetrySystemDialog)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setBaseSize(QtCore.QSize(0, 800))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 474, 1000))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 1000))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(141, 31))
        self.label_3.setMaximumSize(QtCore.QSize(141, 31))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(81, 31))
        self.label_4.setMaximumSize(QtCore.QSize(81, 31))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.label_5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(91, 31))
        self.label_5.setMaximumSize(QtCore.QSize(91, 31))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        spacerItem9 = QtGui.QSpacerItem(101, 27, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.SubsysBrowser_0 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_0.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_0.setSizePolicy(sizePolicy)
        self.SubsysBrowser_0.setMinimumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_0.setMaximumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_0.setObjectName(_fromUtf8("SubsysBrowser_0"))
        self.horizontalLayout_6.addWidget(self.SubsysBrowser_0)
        self.pktidBrowser_0 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pktidBrowser_0.sizePolicy().hasHeightForWidth())
        self.pktidBrowser_0.setSizePolicy(sizePolicy)
        self.pktidBrowser_0.setMinimumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_0.setMaximumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_0.setObjectName(_fromUtf8("pktidBrowser_0"))
        self.horizontalLayout_6.addWidget(self.pktidBrowser_0)
        self.countBrowser_0 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countBrowser_0.sizePolicy().hasHeightForWidth())
        self.countBrowser_0.setSizePolicy(sizePolicy)
        self.countBrowser_0.setMinimumSize(QtCore.QSize(91, 31))
        self.countBrowser_0.setMaximumSize(QtCore.QSize(91, 31))
        self.countBrowser_0.setObjectName(_fromUtf8("countBrowser_0"))
        self.horizontalLayout_6.addWidget(self.countBrowser_0)
        self.pushButton_0 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_0.sizePolicy().hasHeightForWidth())
        self.pushButton_0.setSizePolicy(sizePolicy)
        self.pushButton_0.setMinimumSize(QtCore.QSize(101, 27))
        self.pushButton_0.setMaximumSize(QtCore.QSize(101, 27))
        self.pushButton_0.setObjectName(_fromUtf8("pushButton_0"))
        self.horizontalLayout_6.addWidget(self.pushButton_0)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.SubsysBrowser_1 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_1.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_1.setSizePolicy(sizePolicy)
        self.SubsysBrowser_1.setMinimumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_1.setMaximumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_1.setObjectName(_fromUtf8("SubsysBrowser_1"))
        self.horizontalLayout_7.addWidget(self.SubsysBrowser_1)
        self.pktidBrowser_1 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pktidBrowser_1.sizePolicy().hasHeightForWidth())
        self.pktidBrowser_1.setSizePolicy(sizePolicy)
        self.pktidBrowser_1.setMinimumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_1.setMaximumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_1.setObjectName(_fromUtf8("pktidBrowser_1"))
        self.horizontalLayout_7.addWidget(self.pktidBrowser_1)
        self.countBrowser_1 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countBrowser_1.sizePolicy().hasHeightForWidth())
        self.countBrowser_1.setSizePolicy(sizePolicy)
        self.countBrowser_1.setMinimumSize(QtCore.QSize(91, 31))
        self.countBrowser_1.setMaximumSize(QtCore.QSize(91, 31))
        self.countBrowser_1.setObjectName(_fromUtf8("countBrowser_1"))
        self.horizontalLayout_7.addWidget(self.countBrowser_1)
        self.pushButton_1 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_1.sizePolicy().hasHeightForWidth())
        self.pushButton_1.setSizePolicy(sizePolicy)
        self.pushButton_1.setMinimumSize(QtCore.QSize(101, 27))
        self.pushButton_1.setMaximumSize(QtCore.QSize(101, 27))
        self.pushButton_1.setObjectName(_fromUtf8("pushButton_1"))
        self.horizontalLayout_7.addWidget(self.pushButton_1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.SubsysBrowser_2 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_2.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_2.setSizePolicy(sizePolicy)
        self.SubsysBrowser_2.setMinimumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_2.setMaximumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_2.setObjectName(_fromUtf8("SubsysBrowser_2"))
        self.horizontalLayout_8.addWidget(self.SubsysBrowser_2)
        self.pktidBrowser_2 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pktidBrowser_2.sizePolicy().hasHeightForWidth())
        self.pktidBrowser_2.setSizePolicy(sizePolicy)
        self.pktidBrowser_2.setMinimumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_2.setMaximumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_2.setObjectName(_fromUtf8("pktidBrowser_2"))
        self.horizontalLayout_8.addWidget(self.pktidBrowser_2)
        self.countBrowser_2 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countBrowser_2.sizePolicy().hasHeightForWidth())
        self.countBrowser_2.setSizePolicy(sizePolicy)
        self.countBrowser_2.setMinimumSize(QtCore.QSize(91, 31))
        self.countBrowser_2.setMaximumSize(QtCore.QSize(91, 31))
        self.countBrowser_2.setObjectName(_fromUtf8("countBrowser_2"))
        self.horizontalLayout_8.addWidget(self.countBrowser_2)
        self.pushButton_2 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(101, 27))
        self.pushButton_2.setMaximumSize(QtCore.QSize(101, 27))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_8.addWidget(self.pushButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.SubsysBrowser_3 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_3.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_3.setSizePolicy(sizePolicy)
        self.SubsysBrowser_3.setMinimumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_3.setMaximumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_3.setObjectName(_fromUtf8("SubsysBrowser_3"))
        self.horizontalLayout_9.addWidget(self.SubsysBrowser_3)
        self.pktidBrowser_3 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pktidBrowser_3.sizePolicy().hasHeightForWidth())
        self.pktidBrowser_3.setSizePolicy(sizePolicy)
        self.pktidBrowser_3.setMinimumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_3.setMaximumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_3.setObjectName(_fromUtf8("pktidBrowser_3"))
        self.horizontalLayout_9.addWidget(self.pktidBrowser_3)
        self.countBrowser_3 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countBrowser_3.sizePolicy().hasHeightForWidth())
        self.countBrowser_3.setSizePolicy(sizePolicy)
        self.countBrowser_3.setMinimumSize(QtCore.QSize(91, 31))
        self.countBrowser_3.setMaximumSize(QtCore.QSize(91, 31))
        self.countBrowser_3.setObjectName(_fromUtf8("countBrowser_3"))
        self.horizontalLayout_9.addWidget(self.countBrowser_3)
        self.pushButton_3 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(101, 27))
        self.pushButton_3.setMaximumSize(QtCore.QSize(101, 27))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_9.addWidget(self.pushButton_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.SubsysBrowser_4 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_4.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_4.setSizePolicy(sizePolicy)
        self.SubsysBrowser_4.setMinimumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_4.setMaximumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_4.setObjectName(_fromUtf8("SubsysBrowser_4"))
        self.horizontalLayout_10.addWidget(self.SubsysBrowser_4)
        self.pktidBrowser_4 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pktidBrowser_4.sizePolicy().hasHeightForWidth())
        self.pktidBrowser_4.setSizePolicy(sizePolicy)
        self.pktidBrowser_4.setMinimumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_4.setMaximumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_4.setObjectName(_fromUtf8("pktidBrowser_4"))
        self.horizontalLayout_10.addWidget(self.pktidBrowser_4)
        self.countBrowser_4 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countBrowser_4.sizePolicy().hasHeightForWidth())
        self.countBrowser_4.setSizePolicy(sizePolicy)
        self.countBrowser_4.setMinimumSize(QtCore.QSize(91, 31))
        self.countBrowser_4.setMaximumSize(QtCore.QSize(91, 31))
        self.countBrowser_4.setObjectName(_fromUtf8("countBrowser_4"))
        self.horizontalLayout_10.addWidget(self.countBrowser_4)
        self.pushButton_4 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(101, 27))
        self.pushButton_4.setMaximumSize(QtCore.QSize(101, 27))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_10.addWidget(self.pushButton_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.SubsysBrowser_5 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_5.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_5.setSizePolicy(sizePolicy)
        self.SubsysBrowser_5.setMinimumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_5.setMaximumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_5.setObjectName(_fromUtf8("SubsysBrowser_5"))
        self.horizontalLayout_11.addWidget(self.SubsysBrowser_5)
        self.pktidBrowser_5 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pktidBrowser_5.sizePolicy().hasHeightForWidth())
        self.pktidBrowser_5.setSizePolicy(sizePolicy)
        self.pktidBrowser_5.setMinimumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_5.setMaximumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_5.setObjectName(_fromUtf8("pktidBrowser_5"))
        self.horizontalLayout_11.addWidget(self.pktidBrowser_5)
        self.countBrowser_5 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countBrowser_5.sizePolicy().hasHeightForWidth())
        self.countBrowser_5.setSizePolicy(sizePolicy)
        self.countBrowser_5.setMinimumSize(QtCore.QSize(91, 31))
        self.countBrowser_5.setMaximumSize(QtCore.QSize(91, 31))
        self.countBrowser_5.setObjectName(_fromUtf8("countBrowser_5"))
        self.horizontalLayout_11.addWidget(self.countBrowser_5)
        self.pushButton_5 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(101, 27))
        self.pushButton_5.setMaximumSize(QtCore.QSize(101, 27))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout_11.addWidget(self.pushButton_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.SubsysBrowser_6 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_6.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_6.setSizePolicy(sizePolicy)
        self.SubsysBrowser_6.setMinimumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_6.setMaximumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_6.setObjectName(_fromUtf8("SubsysBrowser_6"))
        self.horizontalLayout_12.addWidget(self.SubsysBrowser_6)
        self.pktidBrowser_6 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pktidBrowser_6.sizePolicy().hasHeightForWidth())
        self.pktidBrowser_6.setSizePolicy(sizePolicy)
        self.pktidBrowser_6.setMinimumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_6.setMaximumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_6.setObjectName(_fromUtf8("pktidBrowser_6"))
        self.horizontalLayout_12.addWidget(self.pktidBrowser_6)
        self.countBrowser_6 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countBrowser_6.sizePolicy().hasHeightForWidth())
        self.countBrowser_6.setSizePolicy(sizePolicy)
        self.countBrowser_6.setMinimumSize(QtCore.QSize(91, 31))
        self.countBrowser_6.setMaximumSize(QtCore.QSize(91, 31))
        self.countBrowser_6.setObjectName(_fromUtf8("countBrowser_6"))
        self.horizontalLayout_12.addWidget(self.countBrowser_6)
        self.pushButton_6 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMinimumSize(QtCore.QSize(101, 27))
        self.pushButton_6.setMaximumSize(QtCore.QSize(101, 27))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.horizontalLayout_12.addWidget(self.pushButton_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.SubsysBrowser_7 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_7.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_7.setSizePolicy(sizePolicy)
        self.SubsysBrowser_7.setMinimumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_7.setMaximumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_7.setObjectName(_fromUtf8("SubsysBrowser_7"))
        self.horizontalLayout_13.addWidget(self.SubsysBrowser_7)
        self.pktidBrowser_7 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pktidBrowser_7.sizePolicy().hasHeightForWidth())
        self.pktidBrowser_7.setSizePolicy(sizePolicy)
        self.pktidBrowser_7.setMinimumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_7.setMaximumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_7.setObjectName(_fromUtf8("pktidBrowser_7"))
        self.horizontalLayout_13.addWidget(self.pktidBrowser_7)
        self.countBrowser_7 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countBrowser_7.sizePolicy().hasHeightForWidth())
        self.countBrowser_7.setSizePolicy(sizePolicy)
        self.countBrowser_7.setMinimumSize(QtCore.QSize(91, 31))
        self.countBrowser_7.setMaximumSize(QtCore.QSize(91, 31))
        self.countBrowser_7.setObjectName(_fromUtf8("countBrowser_7"))
        self.horizontalLayout_13.addWidget(self.countBrowser_7)
        self.pushButton_7 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMinimumSize(QtCore.QSize(101, 27))
        self.pushButton_7.setMaximumSize(QtCore.QSize(101, 27))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.horizontalLayout_13.addWidget(self.pushButton_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.SubsysBrowser_8 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_8.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_8.setSizePolicy(sizePolicy)
        self.SubsysBrowser_8.setMinimumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_8.setMaximumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_8.setObjectName(_fromUtf8("SubsysBrowser_8"))
        self.horizontalLayout_14.addWidget(self.SubsysBrowser_8)
        self.pktidBrowser_8 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pktidBrowser_8.sizePolicy().hasHeightForWidth())
        self.pktidBrowser_8.setSizePolicy(sizePolicy)
        self.pktidBrowser_8.setMinimumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_8.setMaximumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_8.setObjectName(_fromUtf8("pktidBrowser_8"))
        self.horizontalLayout_14.addWidget(self.pktidBrowser_8)
        self.countBrowser_8 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countBrowser_8.sizePolicy().hasHeightForWidth())
        self.countBrowser_8.setSizePolicy(sizePolicy)
        self.countBrowser_8.setMinimumSize(QtCore.QSize(91, 31))
        self.countBrowser_8.setMaximumSize(QtCore.QSize(91, 31))
        self.countBrowser_8.setObjectName(_fromUtf8("countBrowser_8"))
        self.horizontalLayout_14.addWidget(self.countBrowser_8)
        self.pushButton_8 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMinimumSize(QtCore.QSize(101, 27))
        self.pushButton_8.setMaximumSize(QtCore.QSize(101, 27))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.horizontalLayout_14.addWidget(self.pushButton_8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.SubsysBrowser_9 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_9.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_9.setSizePolicy(sizePolicy)
        self.SubsysBrowser_9.setMinimumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_9.setMaximumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_9.setObjectName(_fromUtf8("SubsysBrowser_9"))
        self.horizontalLayout_15.addWidget(self.SubsysBrowser_9)
        self.pktidBrowser_9 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pktidBrowser_9.sizePolicy().hasHeightForWidth())
        self.pktidBrowser_9.setSizePolicy(sizePolicy)
        self.pktidBrowser_9.setMinimumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_9.setMaximumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_9.setObjectName(_fromUtf8("pktidBrowser_9"))
        self.horizontalLayout_15.addWidget(self.pktidBrowser_9)
        self.countBrowser_9 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countBrowser_9.sizePolicy().hasHeightForWidth())
        self.countBrowser_9.setSizePolicy(sizePolicy)
        self.countBrowser_9.setMinimumSize(QtCore.QSize(91, 31))
        self.countBrowser_9.setMaximumSize(QtCore.QSize(91, 31))
        self.countBrowser_9.setObjectName(_fromUtf8("countBrowser_9"))
        self.horizontalLayout_15.addWidget(self.countBrowser_9)
        self.pushButton_9 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setMinimumSize(QtCore.QSize(101, 27))
        self.pushButton_9.setMaximumSize(QtCore.QSize(101, 27))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.horizontalLayout_15.addWidget(self.pushButton_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.SubsysBrowser_10 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_10.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_10.setSizePolicy(sizePolicy)
        self.SubsysBrowser_10.setMinimumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_10.setMaximumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_10.setObjectName(_fromUtf8("SubsysBrowser_10"))
        self.horizontalLayout_16.addWidget(self.SubsysBrowser_10)
        self.pktidBrowser_10 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pktidBrowser_10.sizePolicy().hasHeightForWidth())
        self.pktidBrowser_10.setSizePolicy(sizePolicy)
        self.pktidBrowser_10.setMinimumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_10.setMaximumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_10.setObjectName(_fromUtf8("pktidBrowser_10"))
        self.horizontalLayout_16.addWidget(self.pktidBrowser_10)
        self.countBrowser_10 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countBrowser_10.sizePolicy().hasHeightForWidth())
        self.countBrowser_10.setSizePolicy(sizePolicy)
        self.countBrowser_10.setMinimumSize(QtCore.QSize(91, 31))
        self.countBrowser_10.setMaximumSize(QtCore.QSize(91, 31))
        self.countBrowser_10.setObjectName(_fromUtf8("countBrowser_10"))
        self.horizontalLayout_16.addWidget(self.countBrowser_10)
        self.pushButton_10 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setMinimumSize(QtCore.QSize(101, 27))
        self.pushButton_10.setMaximumSize(QtCore.QSize(101, 27))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.horizontalLayout_16.addWidget(self.pushButton_10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.SubsysBrowser_11 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_11.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_11.setSizePolicy(sizePolicy)
        self.SubsysBrowser_11.setMinimumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_11.setMaximumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_11.setObjectName(_fromUtf8("SubsysBrowser_11"))
        self.horizontalLayout_17.addWidget(self.SubsysBrowser_11)
        self.pktidBrowser_11 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pktidBrowser_11.sizePolicy().hasHeightForWidth())
        self.pktidBrowser_11.setSizePolicy(sizePolicy)
        self.pktidBrowser_11.setMinimumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_11.setMaximumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_11.setObjectName(_fromUtf8("pktidBrowser_11"))
        self.horizontalLayout_17.addWidget(self.pktidBrowser_11)
        self.countBrowser_11 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countBrowser_11.sizePolicy().hasHeightForWidth())
        self.countBrowser_11.setSizePolicy(sizePolicy)
        self.countBrowser_11.setMinimumSize(QtCore.QSize(91, 31))
        self.countBrowser_11.setMaximumSize(QtCore.QSize(91, 31))
        self.countBrowser_11.setObjectName(_fromUtf8("countBrowser_11"))
        self.horizontalLayout_17.addWidget(self.countBrowser_11)
        self.pushButton_11 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setMinimumSize(QtCore.QSize(101, 27))
        self.pushButton_11.setMaximumSize(QtCore.QSize(101, 27))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.horizontalLayout_17.addWidget(self.pushButton_11)
        self.verticalLayout_2.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.SubsysBrowser_12 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_12.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_12.setSizePolicy(sizePolicy)
        self.SubsysBrowser_12.setMinimumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_12.setMaximumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_12.setObjectName(_fromUtf8("SubsysBrowser_12"))
        self.horizontalLayout_18.addWidget(self.SubsysBrowser_12)
        self.pktidBrowser_12 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pktidBrowser_12.sizePolicy().hasHeightForWidth())
        self.pktidBrowser_12.setSizePolicy(sizePolicy)
        self.pktidBrowser_12.setMinimumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_12.setMaximumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_12.setObjectName(_fromUtf8("pktidBrowser_12"))
        self.horizontalLayout_18.addWidget(self.pktidBrowser_12)
        self.countBrowser_12 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countBrowser_12.sizePolicy().hasHeightForWidth())
        self.countBrowser_12.setSizePolicy(sizePolicy)
        self.countBrowser_12.setMinimumSize(QtCore.QSize(91, 31))
        self.countBrowser_12.setMaximumSize(QtCore.QSize(91, 31))
        self.countBrowser_12.setObjectName(_fromUtf8("countBrowser_12"))
        self.horizontalLayout_18.addWidget(self.countBrowser_12)
        self.pushButton_12 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        self.pushButton_12.setMinimumSize(QtCore.QSize(101, 27))
        self.pushButton_12.setMaximumSize(QtCore.QSize(101, 27))
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.horizontalLayout_18.addWidget(self.pushButton_12)
        self.verticalLayout_2.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.SubsysBrowser_13 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_13.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_13.setSizePolicy(sizePolicy)
        self.SubsysBrowser_13.setMinimumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_13.setMaximumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_13.setObjectName(_fromUtf8("SubsysBrowser_13"))
        self.horizontalLayout_19.addWidget(self.SubsysBrowser_13)
        self.pktidBrowser_13 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pktidBrowser_13.sizePolicy().hasHeightForWidth())
        self.pktidBrowser_13.setSizePolicy(sizePolicy)
        self.pktidBrowser_13.setMinimumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_13.setMaximumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_13.setObjectName(_fromUtf8("pktidBrowser_13"))
        self.horizontalLayout_19.addWidget(self.pktidBrowser_13)
        self.countBrowser_13 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countBrowser_13.sizePolicy().hasHeightForWidth())
        self.countBrowser_13.setSizePolicy(sizePolicy)
        self.countBrowser_13.setMinimumSize(QtCore.QSize(91, 31))
        self.countBrowser_13.setMaximumSize(QtCore.QSize(91, 31))
        self.countBrowser_13.setObjectName(_fromUtf8("countBrowser_13"))
        self.horizontalLayout_19.addWidget(self.countBrowser_13)
        self.pushButton_13 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_13.sizePolicy().hasHeightForWidth())
        self.pushButton_13.setSizePolicy(sizePolicy)
        self.pushButton_13.setMinimumSize(QtCore.QSize(101, 27))
        self.pushButton_13.setMaximumSize(QtCore.QSize(101, 27))
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.horizontalLayout_19.addWidget(self.pushButton_13)
        self.verticalLayout_2.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.SubsysBrowser_14 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_14.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_14.setSizePolicy(sizePolicy)
        self.SubsysBrowser_14.setMinimumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_14.setMaximumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_14.setObjectName(_fromUtf8("SubsysBrowser_14"))
        self.horizontalLayout_20.addWidget(self.SubsysBrowser_14)
        self.pktidBrowser_14 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pktidBrowser_14.sizePolicy().hasHeightForWidth())
        self.pktidBrowser_14.setSizePolicy(sizePolicy)
        self.pktidBrowser_14.setMinimumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_14.setMaximumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_14.setObjectName(_fromUtf8("pktidBrowser_14"))
        self.horizontalLayout_20.addWidget(self.pktidBrowser_14)
        self.countBrowser_14 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countBrowser_14.sizePolicy().hasHeightForWidth())
        self.countBrowser_14.setSizePolicy(sizePolicy)
        self.countBrowser_14.setMinimumSize(QtCore.QSize(91, 31))
        self.countBrowser_14.setMaximumSize(QtCore.QSize(91, 31))
        self.countBrowser_14.setObjectName(_fromUtf8("countBrowser_14"))
        self.horizontalLayout_20.addWidget(self.countBrowser_14)
        self.pushButton_14 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
        self.pushButton_14.setSizePolicy(sizePolicy)
        self.pushButton_14.setMinimumSize(QtCore.QSize(101, 27))
        self.pushButton_14.setMaximumSize(QtCore.QSize(101, 27))
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.horizontalLayout_20.addWidget(self.pushButton_14)
        self.verticalLayout_2.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.SubsysBrowser_15 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_15.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_15.setSizePolicy(sizePolicy)
        self.SubsysBrowser_15.setMinimumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_15.setMaximumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_15.setObjectName(_fromUtf8("SubsysBrowser_15"))
        self.horizontalLayout_21.addWidget(self.SubsysBrowser_15)
        self.pktidBrowser_15 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pktidBrowser_15.sizePolicy().hasHeightForWidth())
        self.pktidBrowser_15.setSizePolicy(sizePolicy)
        self.pktidBrowser_15.setMinimumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_15.setMaximumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_15.setObjectName(_fromUtf8("pktidBrowser_15"))
        self.horizontalLayout_21.addWidget(self.pktidBrowser_15)
        self.countBrowser_15 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countBrowser_15.sizePolicy().hasHeightForWidth())
        self.countBrowser_15.setSizePolicy(sizePolicy)
        self.countBrowser_15.setMinimumSize(QtCore.QSize(91, 31))
        self.countBrowser_15.setMaximumSize(QtCore.QSize(91, 31))
        self.countBrowser_15.setObjectName(_fromUtf8("countBrowser_15"))
        self.horizontalLayout_21.addWidget(self.countBrowser_15)
        self.pushButton_15 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_15.sizePolicy().hasHeightForWidth())
        self.pushButton_15.setSizePolicy(sizePolicy)
        self.pushButton_15.setMinimumSize(QtCore.QSize(101, 27))
        self.pushButton_15.setMaximumSize(QtCore.QSize(101, 27))
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.horizontalLayout_21.addWidget(self.pushButton_15)
        self.verticalLayout_2.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.SubsysBrowser_16 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_16.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_16.setSizePolicy(sizePolicy)
        self.SubsysBrowser_16.setMinimumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_16.setMaximumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_16.setObjectName(_fromUtf8("SubsysBrowser_16"))
        self.horizontalLayout_22.addWidget(self.SubsysBrowser_16)
        self.pktidBrowser_16 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pktidBrowser_16.sizePolicy().hasHeightForWidth())
        self.pktidBrowser_16.setSizePolicy(sizePolicy)
        self.pktidBrowser_16.setMinimumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_16.setMaximumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_16.setObjectName(_fromUtf8("pktidBrowser_16"))
        self.horizontalLayout_22.addWidget(self.pktidBrowser_16)
        self.countBrowser_16 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countBrowser_16.sizePolicy().hasHeightForWidth())
        self.countBrowser_16.setSizePolicy(sizePolicy)
        self.countBrowser_16.setMinimumSize(QtCore.QSize(91, 31))
        self.countBrowser_16.setMaximumSize(QtCore.QSize(91, 31))
        self.countBrowser_16.setObjectName(_fromUtf8("countBrowser_16"))
        self.horizontalLayout_22.addWidget(self.countBrowser_16)
        self.pushButton_16 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_16.sizePolicy().hasHeightForWidth())
        self.pushButton_16.setSizePolicy(sizePolicy)
        self.pushButton_16.setMinimumSize(QtCore.QSize(101, 27))
        self.pushButton_16.setMaximumSize(QtCore.QSize(101, 27))
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.horizontalLayout_22.addWidget(self.pushButton_16)
        self.verticalLayout_2.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.SubsysBrowser_17 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_17.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_17.setSizePolicy(sizePolicy)
        self.SubsysBrowser_17.setMinimumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_17.setMaximumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_17.setObjectName(_fromUtf8("SubsysBrowser_17"))
        self.horizontalLayout_23.addWidget(self.SubsysBrowser_17)
        self.pktidBrowser_17 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pktidBrowser_17.sizePolicy().hasHeightForWidth())
        self.pktidBrowser_17.setSizePolicy(sizePolicy)
        self.pktidBrowser_17.setMinimumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_17.setMaximumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_17.setObjectName(_fromUtf8("pktidBrowser_17"))
        self.horizontalLayout_23.addWidget(self.pktidBrowser_17)
        self.countBrowser_17 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countBrowser_17.sizePolicy().hasHeightForWidth())
        self.countBrowser_17.setSizePolicy(sizePolicy)
        self.countBrowser_17.setMinimumSize(QtCore.QSize(91, 31))
        self.countBrowser_17.setMaximumSize(QtCore.QSize(91, 31))
        self.countBrowser_17.setObjectName(_fromUtf8("countBrowser_17"))
        self.horizontalLayout_23.addWidget(self.countBrowser_17)
        self.pushButton_17 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_17.sizePolicy().hasHeightForWidth())
        self.pushButton_17.setSizePolicy(sizePolicy)
        self.pushButton_17.setMinimumSize(QtCore.QSize(101, 27))
        self.pushButton_17.setMaximumSize(QtCore.QSize(101, 27))
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.horizontalLayout_23.addWidget(self.pushButton_17)
        self.verticalLayout_2.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.SubsysBrowser_18 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_18.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_18.setSizePolicy(sizePolicy)
        self.SubsysBrowser_18.setMinimumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_18.setMaximumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_18.setObjectName(_fromUtf8("SubsysBrowser_18"))
        self.horizontalLayout_24.addWidget(self.SubsysBrowser_18)
        self.pktidBrowser_18 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pktidBrowser_18.sizePolicy().hasHeightForWidth())
        self.pktidBrowser_18.setSizePolicy(sizePolicy)
        self.pktidBrowser_18.setMinimumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_18.setMaximumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_18.setObjectName(_fromUtf8("pktidBrowser_18"))
        self.horizontalLayout_24.addWidget(self.pktidBrowser_18)
        self.countBrowser_18 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countBrowser_18.sizePolicy().hasHeightForWidth())
        self.countBrowser_18.setSizePolicy(sizePolicy)
        self.countBrowser_18.setMinimumSize(QtCore.QSize(91, 31))
        self.countBrowser_18.setMaximumSize(QtCore.QSize(91, 31))
        self.countBrowser_18.setObjectName(_fromUtf8("countBrowser_18"))
        self.horizontalLayout_24.addWidget(self.countBrowser_18)
        self.pushButton_18 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_18.sizePolicy().hasHeightForWidth())
        self.pushButton_18.setSizePolicy(sizePolicy)
        self.pushButton_18.setMinimumSize(QtCore.QSize(101, 27))
        self.pushButton_18.setMaximumSize(QtCore.QSize(101, 27))
        self.pushButton_18.setObjectName(_fromUtf8("pushButton_18"))
        self.horizontalLayout_24.addWidget(self.pushButton_18)
        self.verticalLayout_2.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.SubsysBrowser_19 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_19.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_19.setSizePolicy(sizePolicy)
        self.SubsysBrowser_19.setMinimumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_19.setMaximumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_19.setObjectName(_fromUtf8("SubsysBrowser_19"))
        self.horizontalLayout_25.addWidget(self.SubsysBrowser_19)
        self.pktidBrowser_19 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pktidBrowser_19.sizePolicy().hasHeightForWidth())
        self.pktidBrowser_19.setSizePolicy(sizePolicy)
        self.pktidBrowser_19.setMinimumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_19.setMaximumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_19.setObjectName(_fromUtf8("pktidBrowser_19"))
        self.horizontalLayout_25.addWidget(self.pktidBrowser_19)
        self.countBrowser_19 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countBrowser_19.sizePolicy().hasHeightForWidth())
        self.countBrowser_19.setSizePolicy(sizePolicy)
        self.countBrowser_19.setMinimumSize(QtCore.QSize(91, 31))
        self.countBrowser_19.setMaximumSize(QtCore.QSize(91, 31))
        self.countBrowser_19.setObjectName(_fromUtf8("countBrowser_19"))
        self.horizontalLayout_25.addWidget(self.countBrowser_19)
        self.pushButton_19 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_19.sizePolicy().hasHeightForWidth())
        self.pushButton_19.setSizePolicy(sizePolicy)
        self.pushButton_19.setMinimumSize(QtCore.QSize(101, 27))
        self.pushButton_19.setMaximumSize(QtCore.QSize(101, 27))
        self.pushButton_19.setObjectName(_fromUtf8("pushButton_19"))
        self.horizontalLayout_25.addWidget(self.pushButton_19)
        self.verticalLayout_2.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.SubsysBrowser_20 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_20.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_20.setSizePolicy(sizePolicy)
        self.SubsysBrowser_20.setMinimumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_20.setMaximumSize(QtCore.QSize(141, 31))
        self.SubsysBrowser_20.setObjectName(_fromUtf8("SubsysBrowser_20"))
        self.horizontalLayout_26.addWidget(self.SubsysBrowser_20)
        self.pktidBrowser_20 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pktidBrowser_20.sizePolicy().hasHeightForWidth())
        self.pktidBrowser_20.setSizePolicy(sizePolicy)
        self.pktidBrowser_20.setMinimumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_20.setMaximumSize(QtCore.QSize(81, 31))
        self.pktidBrowser_20.setObjectName(_fromUtf8("pktidBrowser_20"))
        self.horizontalLayout_26.addWidget(self.pktidBrowser_20)
        self.countBrowser_20 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countBrowser_20.sizePolicy().hasHeightForWidth())
        self.countBrowser_20.setSizePolicy(sizePolicy)
        self.countBrowser_20.setMinimumSize(QtCore.QSize(91, 31))
        self.countBrowser_20.setMaximumSize(QtCore.QSize(91, 31))
        self.countBrowser_20.setObjectName(_fromUtf8("countBrowser_20"))
        self.horizontalLayout_26.addWidget(self.countBrowser_20)
        self.pushButton_20 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_20.sizePolicy().hasHeightForWidth())
        self.pushButton_20.setSizePolicy(sizePolicy)
        self.pushButton_20.setMinimumSize(QtCore.QSize(101, 27))
        self.pushButton_20.setMaximumSize(QtCore.QSize(101, 27))
        self.pushButton_20.setObjectName(_fromUtf8("pushButton_20"))
        self.horizontalLayout_26.addWidget(self.pushButton_20)
        self.verticalLayout_2.addLayout(self.horizontalLayout_26)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(TelemetrySystemDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), TelemetrySystemDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), TelemetrySystemDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(TelemetrySystemDialog)

    def retranslateUi(self, TelemetrySystemDialog):
        TelemetrySystemDialog.setWindowTitle(_translate("TelemetrySystemDialog", "Dialog", None))
        self.label.setText(_translate("TelemetrySystemDialog", "cFE/CFS Subsystem Telemetry", None))
        self.label_6.setText(_translate("TelemetrySystemDialog", "Packets Received", None))
        self.label_2.setText(_translate("TelemetrySystemDialog", "Available Pages", None))
        self.label_3.setText(_translate("TelemetrySystemDialog", "Subsystem/Page", None))
        self.label_4.setText(_translate("TelemetrySystemDialog", "Packet ID", None))
        self.label_5.setText(_translate("TelemetrySystemDialog", "Packet Count", None))
        self.pushButton_0.setText(_translate("TelemetrySystemDialog", "Display Page", None))
        self.pushButton_1.setText(_translate("TelemetrySystemDialog", "Display Page", None))
        self.pushButton_2.setText(_translate("TelemetrySystemDialog", "Display Page", None))
        self.pushButton_3.setText(_translate("TelemetrySystemDialog", "Display Page", None))
        self.pushButton_4.setText(_translate("TelemetrySystemDialog", "Display Page", None))
        self.pushButton_5.setText(_translate("TelemetrySystemDialog", "Display Page", None))
        self.pushButton_6.setText(_translate("TelemetrySystemDialog", "Display Page", None))
        self.pushButton_7.setText(_translate("TelemetrySystemDialog", "Display Page", None))
        self.pushButton_8.setText(_translate("TelemetrySystemDialog", "Display Page", None))
        self.pushButton_9.setText(_translate("TelemetrySystemDialog", "Display Page", None))
        self.pushButton_10.setText(_translate("TelemetrySystemDialog", "Display Page", None))
        self.pushButton_11.setText(_translate("TelemetrySystemDialog", "Display Page", None))
        self.pushButton_12.setText(_translate("TelemetrySystemDialog", "Display Page", None))
        self.pushButton_13.setText(_translate("TelemetrySystemDialog", "Display Page", None))
        self.pushButton_14.setText(_translate("TelemetrySystemDialog", "Display Page", None))
        self.pushButton_15.setText(_translate("TelemetrySystemDialog", "Display Page", None))
        self.pushButton_16.setText(_translate("TelemetrySystemDialog", "Display Page", None))
        self.pushButton_17.setText(_translate("TelemetrySystemDialog", "Display Page", None))
        self.pushButton_18.setText(_translate("TelemetrySystemDialog", "Display Page", None))
        self.pushButton_19.setText(_translate("TelemetrySystemDialog", "Display Page", None))
        self.pushButton_20.setText(_translate("TelemetrySystemDialog", "Display Page", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    TelemetrySystemDialog = QtGui.QDialog()
    ui = Ui_TelemetrySystemDialog()
    ui.setupUi(TelemetrySystemDialog)
    TelemetrySystemDialog.show()
    sys.exit(app.exec_())

