# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CommandSystemDialog.ui'
#
# Created: Fri Jun 19 20:08:08 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CommandSystemDialog(object):
    def setupUi(self, CommandSystemDialog):
        CommandSystemDialog.setObjectName(_fromUtf8("CommandSystemDialog"))
        CommandSystemDialog.setWindowModality(QtCore.Qt.NonModal)
        CommandSystemDialog.setEnabled(True)
        CommandSystemDialog.resize(709, 581)
        self.verticalLayout = QtGui.QVBoxLayout(CommandSystemDialog)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtGui.QLabel(CommandSystemDialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem2 = QtGui.QSpacerItem(90, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.label_2 = QtGui.QLabel(CommandSystemDialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.buttonBox = QtGui.QDialogButtonBox(CommandSystemDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setMinimumSize(QtCore.QSize(90, 0))
        self.buttonBox.setMaximumSize(QtCore.QSize(90, 16777215))
        self.buttonBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.scrollArea = QtGui.QScrollArea(CommandSystemDialog)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setBaseSize(QtCore.QSize(0, 800))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 668, 1000))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 1000))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(201, 31))
        self.label_3.setMaximumSize(QtCore.QSize(201, 31))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_6.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(81, 31))
        self.label_4.setMaximumSize(QtCore.QSize(81, 31))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_6.addWidget(self.label_4)
        self.label_5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(81, 31))
        self.label_5.setMaximumSize(QtCore.QSize(81, 31))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_6.addWidget(self.label_5)
        spacerItem5 = QtGui.QSpacerItem(101, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        spacerItem6 = QtGui.QSpacerItem(121, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.SubsysBrowser_0 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_0.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_0.setSizePolicy(sizePolicy)
        self.SubsysBrowser_0.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_0.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_0.setObjectName(_fromUtf8("SubsysBrowser_0"))
        self.horizontalLayout_3.addWidget(self.SubsysBrowser_0)
        self.lineEditPktId_0 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_0.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_0.setSizePolicy(sizePolicy)
        self.lineEditPktId_0.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_0.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_0.setObjectName(_fromUtf8("lineEditPktId_0"))
        self.horizontalLayout_3.addWidget(self.lineEditPktId_0)
        self.lineEdit_0 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_0.sizePolicy().hasHeightForWidth())
        self.lineEdit_0.setSizePolicy(sizePolicy)
        self.lineEdit_0.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_0.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_0.setObjectName(_fromUtf8("lineEdit_0"))
        self.horizontalLayout_3.addWidget(self.lineEdit_0)
        self.pushButton_0 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_0.sizePolicy().hasHeightForWidth())
        self.pushButton_0.setSizePolicy(sizePolicy)
        self.pushButton_0.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_0.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_0.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_0.setObjectName(_fromUtf8("pushButton_0"))
        self.horizontalLayout_3.addWidget(self.pushButton_0)
        self.quickButton_1 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_1.sizePolicy().hasHeightForWidth())
        self.quickButton_1.setSizePolicy(sizePolicy)
        self.quickButton_1.setMinimumSize(QtCore.QSize(121, 0))
        self.quickButton_1.setMaximumSize(QtCore.QSize(121, 16777215))
        self.quickButton_1.setText(_fromUtf8(""))
        self.quickButton_1.setObjectName(_fromUtf8("quickButton_1"))
        self.horizontalLayout_3.addWidget(self.quickButton_1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.SubsysBrowser_1 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_1.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_1.setSizePolicy(sizePolicy)
        self.SubsysBrowser_1.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_1.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_1.setObjectName(_fromUtf8("SubsysBrowser_1"))
        self.horizontalLayout_4.addWidget(self.SubsysBrowser_1)
        self.lineEditPktId_1 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_1.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_1.setSizePolicy(sizePolicy)
        self.lineEditPktId_1.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_1.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_1.setObjectName(_fromUtf8("lineEditPktId_1"))
        self.horizontalLayout_4.addWidget(self.lineEditPktId_1)
        self.lineEdit_1 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_1.sizePolicy().hasHeightForWidth())
        self.lineEdit_1.setSizePolicy(sizePolicy)
        self.lineEdit_1.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_1.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_1.setObjectName(_fromUtf8("lineEdit_1"))
        self.horizontalLayout_4.addWidget(self.lineEdit_1)
        self.pushButton_1 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_1.sizePolicy().hasHeightForWidth())
        self.pushButton_1.setSizePolicy(sizePolicy)
        self.pushButton_1.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_1.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_1.setObjectName(_fromUtf8("pushButton_1"))
        self.horizontalLayout_4.addWidget(self.pushButton_1)
        self.quickButton_2 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_2.sizePolicy().hasHeightForWidth())
        self.quickButton_2.setSizePolicy(sizePolicy)
        self.quickButton_2.setMinimumSize(QtCore.QSize(121, 0))
        self.quickButton_2.setMaximumSize(QtCore.QSize(121, 16777215))
        self.quickButton_2.setText(_fromUtf8(""))
        self.quickButton_2.setObjectName(_fromUtf8("quickButton_2"))
        self.horizontalLayout_4.addWidget(self.quickButton_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.SubsysBrowser_2 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_2.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_2.setSizePolicy(sizePolicy)
        self.SubsysBrowser_2.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_2.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_2.setObjectName(_fromUtf8("SubsysBrowser_2"))
        self.horizontalLayout_5.addWidget(self.SubsysBrowser_2)
        self.lineEditPktId_2 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_2.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_2.setSizePolicy(sizePolicy)
        self.lineEditPktId_2.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_2.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_2.setObjectName(_fromUtf8("lineEditPktId_2"))
        self.horizontalLayout_5.addWidget(self.lineEditPktId_2)
        self.lineEdit_2 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout_5.addWidget(self.lineEdit_2)
        self.pushButton_2 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_2.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_5.addWidget(self.pushButton_2)
        self.quickButton_3 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_3.sizePolicy().hasHeightForWidth())
        self.quickButton_3.setSizePolicy(sizePolicy)
        self.quickButton_3.setMinimumSize(QtCore.QSize(121, 0))
        self.quickButton_3.setMaximumSize(QtCore.QSize(121, 16777215))
        self.quickButton_3.setText(_fromUtf8(""))
        self.quickButton_3.setObjectName(_fromUtf8("quickButton_3"))
        self.horizontalLayout_5.addWidget(self.quickButton_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.SubsysBrowser_3 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_3.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_3.setSizePolicy(sizePolicy)
        self.SubsysBrowser_3.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_3.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_3.setObjectName(_fromUtf8("SubsysBrowser_3"))
        self.horizontalLayout_7.addWidget(self.SubsysBrowser_3)
        self.lineEditPktId_3 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_3.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_3.setSizePolicy(sizePolicy)
        self.lineEditPktId_3.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_3.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_3.setObjectName(_fromUtf8("lineEditPktId_3"))
        self.horizontalLayout_7.addWidget(self.lineEditPktId_3)
        self.lineEdit_3 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.horizontalLayout_7.addWidget(self.lineEdit_3)
        self.pushButton_3 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_3.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_7.addWidget(self.pushButton_3)
        self.quickButton_4 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_4.sizePolicy().hasHeightForWidth())
        self.quickButton_4.setSizePolicy(sizePolicy)
        self.quickButton_4.setMinimumSize(QtCore.QSize(121, 0))
        self.quickButton_4.setMaximumSize(QtCore.QSize(121, 16777215))
        self.quickButton_4.setText(_fromUtf8(""))
        self.quickButton_4.setObjectName(_fromUtf8("quickButton_4"))
        self.horizontalLayout_7.addWidget(self.quickButton_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.SubsysBrowser_4 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_4.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_4.setSizePolicy(sizePolicy)
        self.SubsysBrowser_4.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_4.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_4.setObjectName(_fromUtf8("SubsysBrowser_4"))
        self.horizontalLayout_8.addWidget(self.SubsysBrowser_4)
        self.lineEditPktId_4 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_4.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_4.setSizePolicy(sizePolicy)
        self.lineEditPktId_4.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_4.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_4.setObjectName(_fromUtf8("lineEditPktId_4"))
        self.horizontalLayout_8.addWidget(self.lineEditPktId_4)
        self.lineEdit_4 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(sizePolicy)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.horizontalLayout_8.addWidget(self.lineEdit_4)
        self.pushButton_4 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_4.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_8.addWidget(self.pushButton_4)
        self.quickButton_5 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_5.sizePolicy().hasHeightForWidth())
        self.quickButton_5.setSizePolicy(sizePolicy)
        self.quickButton_5.setMinimumSize(QtCore.QSize(121, 0))
        self.quickButton_5.setMaximumSize(QtCore.QSize(121, 16777215))
        self.quickButton_5.setText(_fromUtf8(""))
        self.quickButton_5.setObjectName(_fromUtf8("quickButton_5"))
        self.horizontalLayout_8.addWidget(self.quickButton_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.SubsysBrowser_5 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_5.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_5.setSizePolicy(sizePolicy)
        self.SubsysBrowser_5.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_5.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_5.setObjectName(_fromUtf8("SubsysBrowser_5"))
        self.horizontalLayout_9.addWidget(self.SubsysBrowser_5)
        self.lineEditPktId_5 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_5.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_5.setSizePolicy(sizePolicy)
        self.lineEditPktId_5.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_5.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_5.setObjectName(_fromUtf8("lineEditPktId_5"))
        self.horizontalLayout_9.addWidget(self.lineEditPktId_5)
        self.lineEdit_5 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_5.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.horizontalLayout_9.addWidget(self.lineEdit_5)
        self.pushButton_5 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_5.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout_9.addWidget(self.pushButton_5)
        self.quickButton_6 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_6.sizePolicy().hasHeightForWidth())
        self.quickButton_6.setSizePolicy(sizePolicy)
        self.quickButton_6.setMinimumSize(QtCore.QSize(121, 0))
        self.quickButton_6.setMaximumSize(QtCore.QSize(121, 16777215))
        self.quickButton_6.setText(_fromUtf8(""))
        self.quickButton_6.setObjectName(_fromUtf8("quickButton_6"))
        self.horizontalLayout_9.addWidget(self.quickButton_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.SubsysBrowser_6 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_6.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_6.setSizePolicy(sizePolicy)
        self.SubsysBrowser_6.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_6.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_6.setObjectName(_fromUtf8("SubsysBrowser_6"))
        self.horizontalLayout_10.addWidget(self.SubsysBrowser_6)
        self.lineEditPktId_6 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_6.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_6.setSizePolicy(sizePolicy)
        self.lineEditPktId_6.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_6.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_6.setObjectName(_fromUtf8("lineEditPktId_6"))
        self.horizontalLayout_10.addWidget(self.lineEditPktId_6)
        self.lineEdit_6 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_6.sizePolicy().hasHeightForWidth())
        self.lineEdit_6.setSizePolicy(sizePolicy)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_6.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.horizontalLayout_10.addWidget(self.lineEdit_6)
        self.pushButton_6 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_6.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.horizontalLayout_10.addWidget(self.pushButton_6)
        self.quickButton_7 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_7.sizePolicy().hasHeightForWidth())
        self.quickButton_7.setSizePolicy(sizePolicy)
        self.quickButton_7.setMinimumSize(QtCore.QSize(121, 0))
        self.quickButton_7.setMaximumSize(QtCore.QSize(121, 16777215))
        self.quickButton_7.setText(_fromUtf8(""))
        self.quickButton_7.setObjectName(_fromUtf8("quickButton_7"))
        self.horizontalLayout_10.addWidget(self.quickButton_7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.SubsysBrowser_7 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_7.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_7.setSizePolicy(sizePolicy)
        self.SubsysBrowser_7.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_7.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_7.setObjectName(_fromUtf8("SubsysBrowser_7"))
        self.horizontalLayout_11.addWidget(self.SubsysBrowser_7)
        self.lineEditPktId_7 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_7.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_7.setSizePolicy(sizePolicy)
        self.lineEditPktId_7.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_7.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_7.setObjectName(_fromUtf8("lineEditPktId_7"))
        self.horizontalLayout_11.addWidget(self.lineEditPktId_7)
        self.lineEdit_7 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_7.sizePolicy().hasHeightForWidth())
        self.lineEdit_7.setSizePolicy(sizePolicy)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_7.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.horizontalLayout_11.addWidget(self.lineEdit_7)
        self.pushButton_7 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_7.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.horizontalLayout_11.addWidget(self.pushButton_7)
        self.quickButton_8 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_8.sizePolicy().hasHeightForWidth())
        self.quickButton_8.setSizePolicy(sizePolicy)
        self.quickButton_8.setMinimumSize(QtCore.QSize(121, 0))
        self.quickButton_8.setMaximumSize(QtCore.QSize(121, 16777215))
        self.quickButton_8.setText(_fromUtf8(""))
        self.quickButton_8.setObjectName(_fromUtf8("quickButton_8"))
        self.horizontalLayout_11.addWidget(self.quickButton_8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.SubsysBrowser_8 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_8.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_8.setSizePolicy(sizePolicy)
        self.SubsysBrowser_8.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_8.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_8.setObjectName(_fromUtf8("SubsysBrowser_8"))
        self.horizontalLayout_12.addWidget(self.SubsysBrowser_8)
        self.lineEditPktId_8 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_8.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_8.setSizePolicy(sizePolicy)
        self.lineEditPktId_8.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_8.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_8.setObjectName(_fromUtf8("lineEditPktId_8"))
        self.horizontalLayout_12.addWidget(self.lineEditPktId_8)
        self.lineEdit_8 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_8.sizePolicy().hasHeightForWidth())
        self.lineEdit_8.setSizePolicy(sizePolicy)
        self.lineEdit_8.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_8.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.horizontalLayout_12.addWidget(self.lineEdit_8)
        self.pushButton_8 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_8.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.horizontalLayout_12.addWidget(self.pushButton_8)
        self.quickButton_9 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_9.sizePolicy().hasHeightForWidth())
        self.quickButton_9.setSizePolicy(sizePolicy)
        self.quickButton_9.setMinimumSize(QtCore.QSize(121, 0))
        self.quickButton_9.setMaximumSize(QtCore.QSize(121, 16777215))
        self.quickButton_9.setText(_fromUtf8(""))
        self.quickButton_9.setObjectName(_fromUtf8("quickButton_9"))
        self.horizontalLayout_12.addWidget(self.quickButton_9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.SubsysBrowser_9 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_9.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_9.setSizePolicy(sizePolicy)
        self.SubsysBrowser_9.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_9.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_9.setObjectName(_fromUtf8("SubsysBrowser_9"))
        self.horizontalLayout_13.addWidget(self.SubsysBrowser_9)
        self.lineEditPktId_9 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_9.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_9.setSizePolicy(sizePolicy)
        self.lineEditPktId_9.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_9.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_9.setObjectName(_fromUtf8("lineEditPktId_9"))
        self.horizontalLayout_13.addWidget(self.lineEditPktId_9)
        self.lineEdit_9 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_9.sizePolicy().hasHeightForWidth())
        self.lineEdit_9.setSizePolicy(sizePolicy)
        self.lineEdit_9.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_9.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.horizontalLayout_13.addWidget(self.lineEdit_9)
        self.pushButton_9 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_9.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_9.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.horizontalLayout_13.addWidget(self.pushButton_9)
        self.quickButton_10 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_10.sizePolicy().hasHeightForWidth())
        self.quickButton_10.setSizePolicy(sizePolicy)
        self.quickButton_10.setMinimumSize(QtCore.QSize(121, 0))
        self.quickButton_10.setMaximumSize(QtCore.QSize(121, 16777215))
        self.quickButton_10.setText(_fromUtf8(""))
        self.quickButton_10.setObjectName(_fromUtf8("quickButton_10"))
        self.horizontalLayout_13.addWidget(self.quickButton_10)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.SubsysBrowser_10 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_10.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_10.setSizePolicy(sizePolicy)
        self.SubsysBrowser_10.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_10.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_10.setObjectName(_fromUtf8("SubsysBrowser_10"))
        self.horizontalLayout_14.addWidget(self.SubsysBrowser_10)
        self.lineEditPktId_10 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_10.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_10.setSizePolicy(sizePolicy)
        self.lineEditPktId_10.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_10.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_10.setObjectName(_fromUtf8("lineEditPktId_10"))
        self.horizontalLayout_14.addWidget(self.lineEditPktId_10)
        self.lineEdit_10 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_10.sizePolicy().hasHeightForWidth())
        self.lineEdit_10.setSizePolicy(sizePolicy)
        self.lineEdit_10.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_10.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.horizontalLayout_14.addWidget(self.lineEdit_10)
        self.pushButton_10 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_10.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_10.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.horizontalLayout_14.addWidget(self.pushButton_10)
        self.quickButton_11 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_11.sizePolicy().hasHeightForWidth())
        self.quickButton_11.setSizePolicy(sizePolicy)
        self.quickButton_11.setMinimumSize(QtCore.QSize(121, 0))
        self.quickButton_11.setMaximumSize(QtCore.QSize(121, 16777215))
        self.quickButton_11.setText(_fromUtf8(""))
        self.quickButton_11.setObjectName(_fromUtf8("quickButton_11"))
        self.horizontalLayout_14.addWidget(self.quickButton_11)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.SubsysBrowser_11 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_11.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_11.setSizePolicy(sizePolicy)
        self.SubsysBrowser_11.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_11.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_11.setObjectName(_fromUtf8("SubsysBrowser_11"))
        self.horizontalLayout_15.addWidget(self.SubsysBrowser_11)
        self.lineEditPktId_11 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_11.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_11.setSizePolicy(sizePolicy)
        self.lineEditPktId_11.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_11.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_11.setObjectName(_fromUtf8("lineEditPktId_11"))
        self.horizontalLayout_15.addWidget(self.lineEditPktId_11)
        self.lineEdit_11 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_11.sizePolicy().hasHeightForWidth())
        self.lineEdit_11.setSizePolicy(sizePolicy)
        self.lineEdit_11.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_11.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.horizontalLayout_15.addWidget(self.lineEdit_11)
        self.pushButton_11 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_11.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_11.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.horizontalLayout_15.addWidget(self.pushButton_11)
        self.quickButton_12 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_12.sizePolicy().hasHeightForWidth())
        self.quickButton_12.setSizePolicy(sizePolicy)
        self.quickButton_12.setMinimumSize(QtCore.QSize(121, 0))
        self.quickButton_12.setMaximumSize(QtCore.QSize(121, 16777215))
        self.quickButton_12.setText(_fromUtf8(""))
        self.quickButton_12.setObjectName(_fromUtf8("quickButton_12"))
        self.horizontalLayout_15.addWidget(self.quickButton_12)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.SubsysBrowser_12 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_12.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_12.setSizePolicy(sizePolicy)
        self.SubsysBrowser_12.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_12.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_12.setObjectName(_fromUtf8("SubsysBrowser_12"))
        self.horizontalLayout_16.addWidget(self.SubsysBrowser_12)
        self.lineEditPktId_12 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_12.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_12.setSizePolicy(sizePolicy)
        self.lineEditPktId_12.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_12.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_12.setObjectName(_fromUtf8("lineEditPktId_12"))
        self.horizontalLayout_16.addWidget(self.lineEditPktId_12)
        self.lineEdit_12 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_12.sizePolicy().hasHeightForWidth())
        self.lineEdit_12.setSizePolicy(sizePolicy)
        self.lineEdit_12.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_12.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.horizontalLayout_16.addWidget(self.lineEdit_12)
        self.pushButton_12 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        self.pushButton_12.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_12.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_12.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.horizontalLayout_16.addWidget(self.pushButton_12)
        self.quickButton_13 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_13.sizePolicy().hasHeightForWidth())
        self.quickButton_13.setSizePolicy(sizePolicy)
        self.quickButton_13.setMinimumSize(QtCore.QSize(121, 32))
        self.quickButton_13.setMaximumSize(QtCore.QSize(121, 32))
        self.quickButton_13.setText(_fromUtf8(""))
        self.quickButton_13.setObjectName(_fromUtf8("quickButton_13"))
        self.horizontalLayout_16.addWidget(self.quickButton_13)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.SubsysBrowser_13 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_13.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_13.setSizePolicy(sizePolicy)
        self.SubsysBrowser_13.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_13.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_13.setObjectName(_fromUtf8("SubsysBrowser_13"))
        self.horizontalLayout_17.addWidget(self.SubsysBrowser_13)
        self.lineEditPktId_13 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_13.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_13.setSizePolicy(sizePolicy)
        self.lineEditPktId_13.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_13.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_13.setObjectName(_fromUtf8("lineEditPktId_13"))
        self.horizontalLayout_17.addWidget(self.lineEditPktId_13)
        self.lineEdit_13 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_13.sizePolicy().hasHeightForWidth())
        self.lineEdit_13.setSizePolicy(sizePolicy)
        self.lineEdit_13.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_13.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.horizontalLayout_17.addWidget(self.lineEdit_13)
        self.pushButton_13 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_13.sizePolicy().hasHeightForWidth())
        self.pushButton_13.setSizePolicy(sizePolicy)
        self.pushButton_13.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_13.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_13.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.horizontalLayout_17.addWidget(self.pushButton_13)
        self.quickButton_14 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_14.sizePolicy().hasHeightForWidth())
        self.quickButton_14.setSizePolicy(sizePolicy)
        self.quickButton_14.setMinimumSize(QtCore.QSize(121, 32))
        self.quickButton_14.setMaximumSize(QtCore.QSize(121, 32))
        self.quickButton_14.setText(_fromUtf8(""))
        self.quickButton_14.setObjectName(_fromUtf8("quickButton_14"))
        self.horizontalLayout_17.addWidget(self.quickButton_14)
        self.verticalLayout_4.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.SubsysBrowser_14 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_14.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_14.setSizePolicy(sizePolicy)
        self.SubsysBrowser_14.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_14.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_14.setObjectName(_fromUtf8("SubsysBrowser_14"))
        self.horizontalLayout_18.addWidget(self.SubsysBrowser_14)
        self.lineEditPktId_14 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_14.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_14.setSizePolicy(sizePolicy)
        self.lineEditPktId_14.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_14.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_14.setObjectName(_fromUtf8("lineEditPktId_14"))
        self.horizontalLayout_18.addWidget(self.lineEditPktId_14)
        self.lineEdit_14 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_14.sizePolicy().hasHeightForWidth())
        self.lineEdit_14.setSizePolicy(sizePolicy)
        self.lineEdit_14.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_14.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.horizontalLayout_18.addWidget(self.lineEdit_14)
        self.pushButton_14 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
        self.pushButton_14.setSizePolicy(sizePolicy)
        self.pushButton_14.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_14.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_14.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.horizontalLayout_18.addWidget(self.pushButton_14)
        self.quickButton_15 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_15.sizePolicy().hasHeightForWidth())
        self.quickButton_15.setSizePolicy(sizePolicy)
        self.quickButton_15.setMinimumSize(QtCore.QSize(121, 32))
        self.quickButton_15.setMaximumSize(QtCore.QSize(121, 32))
        self.quickButton_15.setText(_fromUtf8(""))
        self.quickButton_15.setObjectName(_fromUtf8("quickButton_15"))
        self.horizontalLayout_18.addWidget(self.quickButton_15)
        self.verticalLayout_4.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.SubsysBrowser_15 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_15.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_15.setSizePolicy(sizePolicy)
        self.SubsysBrowser_15.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_15.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_15.setObjectName(_fromUtf8("SubsysBrowser_15"))
        self.horizontalLayout_19.addWidget(self.SubsysBrowser_15)
        self.lineEditPktId_15 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_15.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_15.setSizePolicy(sizePolicy)
        self.lineEditPktId_15.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_15.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_15.setObjectName(_fromUtf8("lineEditPktId_15"))
        self.horizontalLayout_19.addWidget(self.lineEditPktId_15)
        self.lineEdit_15 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_15.sizePolicy().hasHeightForWidth())
        self.lineEdit_15.setSizePolicy(sizePolicy)
        self.lineEdit_15.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_15.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.horizontalLayout_19.addWidget(self.lineEdit_15)
        self.pushButton_15 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_15.sizePolicy().hasHeightForWidth())
        self.pushButton_15.setSizePolicy(sizePolicy)
        self.pushButton_15.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_15.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_15.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.horizontalLayout_19.addWidget(self.pushButton_15)
        self.quickButton_16 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_16.sizePolicy().hasHeightForWidth())
        self.quickButton_16.setSizePolicy(sizePolicy)
        self.quickButton_16.setMinimumSize(QtCore.QSize(121, 32))
        self.quickButton_16.setMaximumSize(QtCore.QSize(121, 32))
        self.quickButton_16.setText(_fromUtf8(""))
        self.quickButton_16.setObjectName(_fromUtf8("quickButton_16"))
        self.horizontalLayout_19.addWidget(self.quickButton_16)
        self.verticalLayout_4.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.SubsysBrowser_16 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_16.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_16.setSizePolicy(sizePolicy)
        self.SubsysBrowser_16.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_16.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_16.setObjectName(_fromUtf8("SubsysBrowser_16"))
        self.horizontalLayout_20.addWidget(self.SubsysBrowser_16)
        self.lineEditPktId_16 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_16.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_16.setSizePolicy(sizePolicy)
        self.lineEditPktId_16.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_16.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_16.setObjectName(_fromUtf8("lineEditPktId_16"))
        self.horizontalLayout_20.addWidget(self.lineEditPktId_16)
        self.lineEdit_16 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_16.sizePolicy().hasHeightForWidth())
        self.lineEdit_16.setSizePolicy(sizePolicy)
        self.lineEdit_16.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_16.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.horizontalLayout_20.addWidget(self.lineEdit_16)
        self.pushButton_16 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_16.sizePolicy().hasHeightForWidth())
        self.pushButton_16.setSizePolicy(sizePolicy)
        self.pushButton_16.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_16.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_16.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.horizontalLayout_20.addWidget(self.pushButton_16)
        self.quickButton_17 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_17.sizePolicy().hasHeightForWidth())
        self.quickButton_17.setSizePolicy(sizePolicy)
        self.quickButton_17.setMinimumSize(QtCore.QSize(121, 32))
        self.quickButton_17.setMaximumSize(QtCore.QSize(121, 32))
        self.quickButton_17.setText(_fromUtf8(""))
        self.quickButton_17.setObjectName(_fromUtf8("quickButton_17"))
        self.horizontalLayout_20.addWidget(self.quickButton_17)
        self.verticalLayout_4.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.SubsysBrowser_17 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_17.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_17.setSizePolicy(sizePolicy)
        self.SubsysBrowser_17.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_17.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_17.setObjectName(_fromUtf8("SubsysBrowser_17"))
        self.horizontalLayout_21.addWidget(self.SubsysBrowser_17)
        self.lineEditPktId_17 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_17.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_17.setSizePolicy(sizePolicy)
        self.lineEditPktId_17.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_17.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_17.setObjectName(_fromUtf8("lineEditPktId_17"))
        self.horizontalLayout_21.addWidget(self.lineEditPktId_17)
        self.lineEdit_17 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_17.sizePolicy().hasHeightForWidth())
        self.lineEdit_17.setSizePolicy(sizePolicy)
        self.lineEdit_17.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_17.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.horizontalLayout_21.addWidget(self.lineEdit_17)
        self.pushButton_17 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_17.sizePolicy().hasHeightForWidth())
        self.pushButton_17.setSizePolicy(sizePolicy)
        self.pushButton_17.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_17.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_17.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.horizontalLayout_21.addWidget(self.pushButton_17)
        self.quickButton_18 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_18.sizePolicy().hasHeightForWidth())
        self.quickButton_18.setSizePolicy(sizePolicy)
        self.quickButton_18.setMinimumSize(QtCore.QSize(121, 32))
        self.quickButton_18.setMaximumSize(QtCore.QSize(121, 32))
        self.quickButton_18.setText(_fromUtf8(""))
        self.quickButton_18.setObjectName(_fromUtf8("quickButton_18"))
        self.horizontalLayout_21.addWidget(self.quickButton_18)
        self.verticalLayout_4.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.SubsysBrowser_18 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_18.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_18.setSizePolicy(sizePolicy)
        self.SubsysBrowser_18.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_18.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_18.setObjectName(_fromUtf8("SubsysBrowser_18"))
        self.horizontalLayout_22.addWidget(self.SubsysBrowser_18)
        self.lineEditPktId_18 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_18.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_18.setSizePolicy(sizePolicy)
        self.lineEditPktId_18.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_18.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_18.setObjectName(_fromUtf8("lineEditPktId_18"))
        self.horizontalLayout_22.addWidget(self.lineEditPktId_18)
        self.lineEdit_18 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_18.sizePolicy().hasHeightForWidth())
        self.lineEdit_18.setSizePolicy(sizePolicy)
        self.lineEdit_18.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_18.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.horizontalLayout_22.addWidget(self.lineEdit_18)
        self.pushButton_18 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_18.sizePolicy().hasHeightForWidth())
        self.pushButton_18.setSizePolicy(sizePolicy)
        self.pushButton_18.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_18.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_18.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_18.setObjectName(_fromUtf8("pushButton_18"))
        self.horizontalLayout_22.addWidget(self.pushButton_18)
        self.quickButton_19 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_19.sizePolicy().hasHeightForWidth())
        self.quickButton_19.setSizePolicy(sizePolicy)
        self.quickButton_19.setMinimumSize(QtCore.QSize(121, 32))
        self.quickButton_19.setMaximumSize(QtCore.QSize(121, 32))
        self.quickButton_19.setText(_fromUtf8(""))
        self.quickButton_19.setObjectName(_fromUtf8("quickButton_19"))
        self.horizontalLayout_22.addWidget(self.quickButton_19)
        self.verticalLayout_4.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.SubsysBrowser_19 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_19.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_19.setSizePolicy(sizePolicy)
        self.SubsysBrowser_19.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_19.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_19.setObjectName(_fromUtf8("SubsysBrowser_19"))
        self.horizontalLayout_23.addWidget(self.SubsysBrowser_19)
        self.lineEditPktId_19 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_19.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_19.setSizePolicy(sizePolicy)
        self.lineEditPktId_19.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_19.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_19.setObjectName(_fromUtf8("lineEditPktId_19"))
        self.horizontalLayout_23.addWidget(self.lineEditPktId_19)
        self.lineEdit_19 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_19.sizePolicy().hasHeightForWidth())
        self.lineEdit_19.setSizePolicy(sizePolicy)
        self.lineEdit_19.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_19.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.horizontalLayout_23.addWidget(self.lineEdit_19)
        self.pushButton_19 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_19.sizePolicy().hasHeightForWidth())
        self.pushButton_19.setSizePolicy(sizePolicy)
        self.pushButton_19.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_19.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_19.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_19.setObjectName(_fromUtf8("pushButton_19"))
        self.horizontalLayout_23.addWidget(self.pushButton_19)
        self.quickButton_20 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_20.sizePolicy().hasHeightForWidth())
        self.quickButton_20.setSizePolicy(sizePolicy)
        self.quickButton_20.setMinimumSize(QtCore.QSize(121, 32))
        self.quickButton_20.setMaximumSize(QtCore.QSize(121, 32))
        self.quickButton_20.setText(_fromUtf8(""))
        self.quickButton_20.setObjectName(_fromUtf8("quickButton_20"))
        self.horizontalLayout_23.addWidget(self.quickButton_20)
        self.verticalLayout_4.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.SubsysBrowser_20 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_20.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_20.setSizePolicy(sizePolicy)
        self.SubsysBrowser_20.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_20.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_20.setObjectName(_fromUtf8("SubsysBrowser_20"))
        self.horizontalLayout_24.addWidget(self.SubsysBrowser_20)
        self.lineEditPktId_20 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_20.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_20.setSizePolicy(sizePolicy)
        self.lineEditPktId_20.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_20.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_20.setObjectName(_fromUtf8("lineEditPktId_20"))
        self.horizontalLayout_24.addWidget(self.lineEditPktId_20)
        self.lineEdit_20 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_20.sizePolicy().hasHeightForWidth())
        self.lineEdit_20.setSizePolicy(sizePolicy)
        self.lineEdit_20.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_20.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.horizontalLayout_24.addWidget(self.lineEdit_20)
        self.pushButton_20 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_20.sizePolicy().hasHeightForWidth())
        self.pushButton_20.setSizePolicy(sizePolicy)
        self.pushButton_20.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_20.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_20.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_20.setObjectName(_fromUtf8("pushButton_20"))
        self.horizontalLayout_24.addWidget(self.pushButton_20)
        self.quickButton_21 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_21.sizePolicy().hasHeightForWidth())
        self.quickButton_21.setSizePolicy(sizePolicy)
        self.quickButton_21.setMinimumSize(QtCore.QSize(121, 32))
        self.quickButton_21.setMaximumSize(QtCore.QSize(121, 32))
        self.quickButton_21.setText(_fromUtf8(""))
        self.quickButton_21.setObjectName(_fromUtf8("quickButton_21"))
        self.horizontalLayout_24.addWidget(self.quickButton_21)
        self.verticalLayout_4.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.SubsysBrowser_21 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_21.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_21.setSizePolicy(sizePolicy)
        self.SubsysBrowser_21.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_21.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_21.setObjectName(_fromUtf8("SubsysBrowser_21"))
        self.horizontalLayout_25.addWidget(self.SubsysBrowser_21)
        self.lineEditPktId_21 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_21.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_21.setSizePolicy(sizePolicy)
        self.lineEditPktId_21.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_21.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_21.setObjectName(_fromUtf8("lineEditPktId_21"))
        self.horizontalLayout_25.addWidget(self.lineEditPktId_21)
        self.lineEdit_21 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_21.sizePolicy().hasHeightForWidth())
        self.lineEdit_21.setSizePolicy(sizePolicy)
        self.lineEdit_21.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_21.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.horizontalLayout_25.addWidget(self.lineEdit_21)
        self.pushButton_21 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_21.sizePolicy().hasHeightForWidth())
        self.pushButton_21.setSizePolicy(sizePolicy)
        self.pushButton_21.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_21.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_21.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_21.setObjectName(_fromUtf8("pushButton_21"))
        self.horizontalLayout_25.addWidget(self.pushButton_21)
        self.quickButton_22 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_22.sizePolicy().hasHeightForWidth())
        self.quickButton_22.setSizePolicy(sizePolicy)
        self.quickButton_22.setMinimumSize(QtCore.QSize(121, 32))
        self.quickButton_22.setMaximumSize(QtCore.QSize(121, 32))
        self.quickButton_22.setText(_fromUtf8(""))
        self.quickButton_22.setObjectName(_fromUtf8("quickButton_22"))
        self.horizontalLayout_25.addWidget(self.quickButton_22)
        self.verticalLayout_4.addLayout(self.horizontalLayout_25)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(CommandSystemDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("clicked(QAbstractButton*)")), CommandSystemDialog.close)
        QtCore.QMetaObject.connectSlotsByName(CommandSystemDialog)

    def retranslateUi(self, CommandSystemDialog):
        CommandSystemDialog.setWindowTitle(_translate("CommandSystemDialog", "Command System", None))
        self.label.setText(_translate("CommandSystemDialog", "cFE/CFS Subsystem Commands", None))
        self.label_2.setText(_translate("CommandSystemDialog", "Available Pages", None))
        self.label_3.setText(_translate("CommandSystemDialog", "Subsystem/Page", None))
        self.label_4.setText(_translate("CommandSystemDialog", "Packet ID", None))
        self.label_5.setText(_translate("CommandSystemDialog", "Send To", None))
        self.pushButton_0.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_1.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_2.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_3.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_4.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_5.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_6.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_7.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_8.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_9.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_10.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_11.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_12.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_13.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_14.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_15.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_16.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_17.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_18.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_19.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_20.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_21.setText(_translate("CommandSystemDialog", "Display Page", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    CommandSystemDialog = QtGui.QWidget()
    ui = Ui_CommandSystemDialog()
    ui.setupUi(CommandSystemDialog)
    CommandSystemDialog.show()
    sys.exit(app.exec_())

