# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GenericCommandDialog.ui'
#
# Created: Wed Mar 25 17:15:12 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GenericCommandDialog(object):
    def setupUi(self, GenericCommandDialog):
        GenericCommandDialog.setObjectName(_fromUtf8("GenericCommandDialog"))
        GenericCommandDialog.resize(549, 504)
        self.verticalLayout_6 = QtGui.QVBoxLayout(GenericCommandDialog)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.subSystemCommandPageLabel = QtGui.QLabel(GenericCommandDialog)
        self.subSystemCommandPageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.subSystemCommandPageLabel.setObjectName(_fromUtf8("subSystemCommandPageLabel"))
        self.verticalLayout.addWidget(self.subSystemCommandPageLabel)
        self.subSystemTextBrowser = QtGui.QTextBrowser(GenericCommandDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subSystemTextBrowser.sizePolicy().hasHeightForWidth())
        self.subSystemTextBrowser.setSizePolicy(sizePolicy)
        self.subSystemTextBrowser.setMinimumSize(QtCore.QSize(159, 31))
        self.subSystemTextBrowser.setMaximumSize(QtCore.QSize(300, 31))
        self.subSystemTextBrowser.setObjectName(_fromUtf8("subSystemTextBrowser"))
        self.verticalLayout.addWidget(self.subSystemTextBrowser)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.packetIdLabel = QtGui.QLabel(GenericCommandDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.packetIdLabel.sizePolicy().hasHeightForWidth())
        self.packetIdLabel.setSizePolicy(sizePolicy)
        self.packetIdLabel.setMinimumSize(QtCore.QSize(0, 13))
        self.packetIdLabel.setMaximumSize(QtCore.QSize(16777193, 13))
        self.packetIdLabel.setObjectName(_fromUtf8("packetIdLabel"))
        self.verticalLayout_2.addWidget(self.packetIdLabel)
        self.packetId = QtGui.QLCDNumber(GenericCommandDialog)
        self.packetId.setObjectName(_fromUtf8("packetId"))
        self.verticalLayout_2.addWidget(self.packetId)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_5 = QtGui.QLabel(GenericCommandDialog)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_3.addWidget(self.label_5)
        self.commandAddressLineEdit = QtGui.QLineEdit(GenericCommandDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandAddressLineEdit.sizePolicy().hasHeightForWidth())
        self.commandAddressLineEdit.setSizePolicy(sizePolicy)
        self.commandAddressLineEdit.setMinimumSize(QtCore.QSize(135, 31))
        self.commandAddressLineEdit.setMaximumSize(QtCore.QSize(135, 31))
        self.commandAddressLineEdit.setObjectName(_fromUtf8("commandAddressLineEdit"))
        self.verticalLayout_3.addWidget(self.commandAddressLineEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.buttonBox = QtGui.QDialogButtonBox(GenericCommandDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.label = QtGui.QLabel(GenericCommandDialog)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_4.addWidget(self.label)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.scrollArea = QtGui.QScrollArea(GenericCommandDialog)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 508, 1000))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 1000))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.itemLabelTextBrowser_1 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_1.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_1.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_1.setMinimumSize(QtCore.QSize(391, 31))
        self.itemLabelTextBrowser_1.setMaximumSize(QtCore.QSize(1234, 31))
        self.itemLabelTextBrowser_1.setObjectName(_fromUtf8("itemLabelTextBrowser_1"))
        self.horizontalLayout_2.addWidget(self.itemLabelTextBrowser_1)
        self.SendButton_1 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SendButton_1.sizePolicy().hasHeightForWidth())
        self.SendButton_1.setSizePolicy(sizePolicy)
        self.SendButton_1.setMinimumSize(QtCore.QSize(73, 32))
        self.SendButton_1.setMaximumSize(QtCore.QSize(73, 32))
        self.SendButton_1.setObjectName(_fromUtf8("SendButton_1"))
        self.horizontalLayout_2.addWidget(self.SendButton_1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.itemLabelTextBrowser_2 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_2.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_2.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_2.setMinimumSize(QtCore.QSize(391, 31))
        self.itemLabelTextBrowser_2.setMaximumSize(QtCore.QSize(1234, 31))
        self.itemLabelTextBrowser_2.setObjectName(_fromUtf8("itemLabelTextBrowser_2"))
        self.horizontalLayout_3.addWidget(self.itemLabelTextBrowser_2)
        self.SendButton_2 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SendButton_2.sizePolicy().hasHeightForWidth())
        self.SendButton_2.setSizePolicy(sizePolicy)
        self.SendButton_2.setMinimumSize(QtCore.QSize(73, 32))
        self.SendButton_2.setMaximumSize(QtCore.QSize(73, 32))
        self.SendButton_2.setObjectName(_fromUtf8("SendButton_2"))
        self.horizontalLayout_3.addWidget(self.SendButton_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.itemLabelTextBrowser_3 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_3.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_3.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_3.setMinimumSize(QtCore.QSize(391, 31))
        self.itemLabelTextBrowser_3.setMaximumSize(QtCore.QSize(1234, 31))
        self.itemLabelTextBrowser_3.setObjectName(_fromUtf8("itemLabelTextBrowser_3"))
        self.horizontalLayout_4.addWidget(self.itemLabelTextBrowser_3)
        self.SendButton_3 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SendButton_3.sizePolicy().hasHeightForWidth())
        self.SendButton_3.setSizePolicy(sizePolicy)
        self.SendButton_3.setMinimumSize(QtCore.QSize(73, 32))
        self.SendButton_3.setMaximumSize(QtCore.QSize(73, 32))
        self.SendButton_3.setObjectName(_fromUtf8("SendButton_3"))
        self.horizontalLayout_4.addWidget(self.SendButton_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.itemLabelTextBrowser_4 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_4.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_4.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_4.setMinimumSize(QtCore.QSize(391, 31))
        self.itemLabelTextBrowser_4.setMaximumSize(QtCore.QSize(1234, 31))
        self.itemLabelTextBrowser_4.setObjectName(_fromUtf8("itemLabelTextBrowser_4"))
        self.horizontalLayout_5.addWidget(self.itemLabelTextBrowser_4)
        self.SendButton_4 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SendButton_4.sizePolicy().hasHeightForWidth())
        self.SendButton_4.setSizePolicy(sizePolicy)
        self.SendButton_4.setMinimumSize(QtCore.QSize(73, 32))
        self.SendButton_4.setMaximumSize(QtCore.QSize(73, 32))
        self.SendButton_4.setObjectName(_fromUtf8("SendButton_4"))
        self.horizontalLayout_5.addWidget(self.SendButton_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.itemLabelTextBrowser_5 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_5.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_5.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_5.setMinimumSize(QtCore.QSize(391, 31))
        self.itemLabelTextBrowser_5.setMaximumSize(QtCore.QSize(1234, 31))
        self.itemLabelTextBrowser_5.setObjectName(_fromUtf8("itemLabelTextBrowser_5"))
        self.horizontalLayout_6.addWidget(self.itemLabelTextBrowser_5)
        self.SendButton_5 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SendButton_5.sizePolicy().hasHeightForWidth())
        self.SendButton_5.setSizePolicy(sizePolicy)
        self.SendButton_5.setMinimumSize(QtCore.QSize(73, 32))
        self.SendButton_5.setMaximumSize(QtCore.QSize(73, 32))
        self.SendButton_5.setObjectName(_fromUtf8("SendButton_5"))
        self.horizontalLayout_6.addWidget(self.SendButton_5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.itemLabelTextBrowser_6 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_6.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_6.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_6.setMinimumSize(QtCore.QSize(391, 31))
        self.itemLabelTextBrowser_6.setMaximumSize(QtCore.QSize(1234, 31))
        self.itemLabelTextBrowser_6.setObjectName(_fromUtf8("itemLabelTextBrowser_6"))
        self.horizontalLayout_7.addWidget(self.itemLabelTextBrowser_6)
        self.SendButton_6 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SendButton_6.sizePolicy().hasHeightForWidth())
        self.SendButton_6.setSizePolicy(sizePolicy)
        self.SendButton_6.setMinimumSize(QtCore.QSize(73, 32))
        self.SendButton_6.setMaximumSize(QtCore.QSize(73, 32))
        self.SendButton_6.setObjectName(_fromUtf8("SendButton_6"))
        self.horizontalLayout_7.addWidget(self.SendButton_6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.itemLabelTextBrowser_7 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_7.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_7.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_7.setMinimumSize(QtCore.QSize(391, 31))
        self.itemLabelTextBrowser_7.setMaximumSize(QtCore.QSize(1234, 31))
        self.itemLabelTextBrowser_7.setObjectName(_fromUtf8("itemLabelTextBrowser_7"))
        self.horizontalLayout_8.addWidget(self.itemLabelTextBrowser_7)
        self.SendButton_7 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SendButton_7.sizePolicy().hasHeightForWidth())
        self.SendButton_7.setSizePolicy(sizePolicy)
        self.SendButton_7.setMinimumSize(QtCore.QSize(73, 32))
        self.SendButton_7.setMaximumSize(QtCore.QSize(73, 32))
        self.SendButton_7.setObjectName(_fromUtf8("SendButton_7"))
        self.horizontalLayout_8.addWidget(self.SendButton_7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.itemLabelTextBrowser_8 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_8.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_8.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_8.setMinimumSize(QtCore.QSize(391, 31))
        self.itemLabelTextBrowser_8.setMaximumSize(QtCore.QSize(1234, 31))
        self.itemLabelTextBrowser_8.setObjectName(_fromUtf8("itemLabelTextBrowser_8"))
        self.horizontalLayout_9.addWidget(self.itemLabelTextBrowser_8)
        self.SendButton_8 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SendButton_8.sizePolicy().hasHeightForWidth())
        self.SendButton_8.setSizePolicy(sizePolicy)
        self.SendButton_8.setMinimumSize(QtCore.QSize(73, 32))
        self.SendButton_8.setMaximumSize(QtCore.QSize(73, 32))
        self.SendButton_8.setObjectName(_fromUtf8("SendButton_8"))
        self.horizontalLayout_9.addWidget(self.SendButton_8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.itemLabelTextBrowser_9 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_9.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_9.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_9.setMinimumSize(QtCore.QSize(391, 31))
        self.itemLabelTextBrowser_9.setMaximumSize(QtCore.QSize(1234, 31))
        self.itemLabelTextBrowser_9.setObjectName(_fromUtf8("itemLabelTextBrowser_9"))
        self.horizontalLayout_10.addWidget(self.itemLabelTextBrowser_9)
        self.SendButton_9 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SendButton_9.sizePolicy().hasHeightForWidth())
        self.SendButton_9.setSizePolicy(sizePolicy)
        self.SendButton_9.setMinimumSize(QtCore.QSize(73, 32))
        self.SendButton_9.setMaximumSize(QtCore.QSize(73, 32))
        self.SendButton_9.setObjectName(_fromUtf8("SendButton_9"))
        self.horizontalLayout_10.addWidget(self.SendButton_9)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.itemLabelTextBrowser_10 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_10.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_10.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_10.setMinimumSize(QtCore.QSize(391, 31))
        self.itemLabelTextBrowser_10.setMaximumSize(QtCore.QSize(1234, 31))
        self.itemLabelTextBrowser_10.setObjectName(_fromUtf8("itemLabelTextBrowser_10"))
        self.horizontalLayout_11.addWidget(self.itemLabelTextBrowser_10)
        self.SendButton_10 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SendButton_10.sizePolicy().hasHeightForWidth())
        self.SendButton_10.setSizePolicy(sizePolicy)
        self.SendButton_10.setMinimumSize(QtCore.QSize(73, 32))
        self.SendButton_10.setMaximumSize(QtCore.QSize(73, 32))
        self.SendButton_10.setObjectName(_fromUtf8("SendButton_10"))
        self.horizontalLayout_11.addWidget(self.SendButton_10)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.itemLabelTextBrowser_11 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_11.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_11.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_11.setMinimumSize(QtCore.QSize(391, 31))
        self.itemLabelTextBrowser_11.setMaximumSize(QtCore.QSize(1234, 31))
        self.itemLabelTextBrowser_11.setObjectName(_fromUtf8("itemLabelTextBrowser_11"))
        self.horizontalLayout_12.addWidget(self.itemLabelTextBrowser_11)
        self.SendButton_11 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SendButton_11.sizePolicy().hasHeightForWidth())
        self.SendButton_11.setSizePolicy(sizePolicy)
        self.SendButton_11.setMinimumSize(QtCore.QSize(73, 32))
        self.SendButton_11.setMaximumSize(QtCore.QSize(73, 32))
        self.SendButton_11.setObjectName(_fromUtf8("SendButton_11"))
        self.horizontalLayout_12.addWidget(self.SendButton_11)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.itemLabelTextBrowser_12 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_12.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_12.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_12.setMinimumSize(QtCore.QSize(391, 31))
        self.itemLabelTextBrowser_12.setMaximumSize(QtCore.QSize(1234, 31))
        self.itemLabelTextBrowser_12.setObjectName(_fromUtf8("itemLabelTextBrowser_12"))
        self.horizontalLayout_13.addWidget(self.itemLabelTextBrowser_12)
        self.SendButton_12 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SendButton_12.sizePolicy().hasHeightForWidth())
        self.SendButton_12.setSizePolicy(sizePolicy)
        self.SendButton_12.setMinimumSize(QtCore.QSize(73, 32))
        self.SendButton_12.setMaximumSize(QtCore.QSize(73, 32))
        self.SendButton_12.setObjectName(_fromUtf8("SendButton_12"))
        self.horizontalLayout_13.addWidget(self.SendButton_12)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.itemLabelTextBrowser_13 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_13.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_13.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_13.setMinimumSize(QtCore.QSize(391, 31))
        self.itemLabelTextBrowser_13.setMaximumSize(QtCore.QSize(1234, 31))
        self.itemLabelTextBrowser_13.setObjectName(_fromUtf8("itemLabelTextBrowser_13"))
        self.horizontalLayout_14.addWidget(self.itemLabelTextBrowser_13)
        self.SendButton_13 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SendButton_13.sizePolicy().hasHeightForWidth())
        self.SendButton_13.setSizePolicy(sizePolicy)
        self.SendButton_13.setMinimumSize(QtCore.QSize(73, 32))
        self.SendButton_13.setMaximumSize(QtCore.QSize(73, 32))
        self.SendButton_13.setObjectName(_fromUtf8("SendButton_13"))
        self.horizontalLayout_14.addWidget(self.SendButton_13)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.itemLabelTextBrowser_14 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_14.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_14.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_14.setMinimumSize(QtCore.QSize(391, 31))
        self.itemLabelTextBrowser_14.setMaximumSize(QtCore.QSize(1234, 31))
        self.itemLabelTextBrowser_14.setObjectName(_fromUtf8("itemLabelTextBrowser_14"))
        self.horizontalLayout_15.addWidget(self.itemLabelTextBrowser_14)
        self.SendButton_14 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SendButton_14.sizePolicy().hasHeightForWidth())
        self.SendButton_14.setSizePolicy(sizePolicy)
        self.SendButton_14.setMinimumSize(QtCore.QSize(73, 32))
        self.SendButton_14.setMaximumSize(QtCore.QSize(73, 32))
        self.SendButton_14.setObjectName(_fromUtf8("SendButton_14"))
        self.horizontalLayout_15.addWidget(self.SendButton_14)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.itemLabelTextBrowser_15 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_15.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_15.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_15.setMinimumSize(QtCore.QSize(391, 31))
        self.itemLabelTextBrowser_15.setMaximumSize(QtCore.QSize(1234, 31))
        self.itemLabelTextBrowser_15.setObjectName(_fromUtf8("itemLabelTextBrowser_15"))
        self.horizontalLayout_16.addWidget(self.itemLabelTextBrowser_15)
        self.SendButton_15 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SendButton_15.sizePolicy().hasHeightForWidth())
        self.SendButton_15.setSizePolicy(sizePolicy)
        self.SendButton_15.setMinimumSize(QtCore.QSize(73, 32))
        self.SendButton_15.setMaximumSize(QtCore.QSize(73, 32))
        self.SendButton_15.setObjectName(_fromUtf8("SendButton_15"))
        self.horizontalLayout_16.addWidget(self.SendButton_15)
        self.verticalLayout_5.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.itemLabelTextBrowser_16 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_16.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_16.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_16.setMinimumSize(QtCore.QSize(391, 31))
        self.itemLabelTextBrowser_16.setMaximumSize(QtCore.QSize(1234, 31))
        self.itemLabelTextBrowser_16.setObjectName(_fromUtf8("itemLabelTextBrowser_16"))
        self.horizontalLayout_17.addWidget(self.itemLabelTextBrowser_16)
        self.SendButton_16 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SendButton_16.sizePolicy().hasHeightForWidth())
        self.SendButton_16.setSizePolicy(sizePolicy)
        self.SendButton_16.setMinimumSize(QtCore.QSize(73, 32))
        self.SendButton_16.setMaximumSize(QtCore.QSize(73, 32))
        self.SendButton_16.setObjectName(_fromUtf8("SendButton_16"))
        self.horizontalLayout_17.addWidget(self.SendButton_16)
        self.verticalLayout_5.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.itemLabelTextBrowser_17 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_17.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_17.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_17.setMinimumSize(QtCore.QSize(391, 31))
        self.itemLabelTextBrowser_17.setMaximumSize(QtCore.QSize(1234, 31))
        self.itemLabelTextBrowser_17.setObjectName(_fromUtf8("itemLabelTextBrowser_17"))
        self.horizontalLayout_18.addWidget(self.itemLabelTextBrowser_17)
        self.SendButton_17 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SendButton_17.sizePolicy().hasHeightForWidth())
        self.SendButton_17.setSizePolicy(sizePolicy)
        self.SendButton_17.setMinimumSize(QtCore.QSize(73, 32))
        self.SendButton_17.setMaximumSize(QtCore.QSize(73, 32))
        self.SendButton_17.setObjectName(_fromUtf8("SendButton_17"))
        self.horizontalLayout_18.addWidget(self.SendButton_17)
        self.verticalLayout_5.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.itemLabelTextBrowser_18 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_18.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_18.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_18.setMinimumSize(QtCore.QSize(391, 31))
        self.itemLabelTextBrowser_18.setMaximumSize(QtCore.QSize(1234, 31))
        self.itemLabelTextBrowser_18.setObjectName(_fromUtf8("itemLabelTextBrowser_18"))
        self.horizontalLayout_19.addWidget(self.itemLabelTextBrowser_18)
        self.SendButton_18 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SendButton_18.sizePolicy().hasHeightForWidth())
        self.SendButton_18.setSizePolicy(sizePolicy)
        self.SendButton_18.setMinimumSize(QtCore.QSize(73, 32))
        self.SendButton_18.setMaximumSize(QtCore.QSize(73, 32))
        self.SendButton_18.setObjectName(_fromUtf8("SendButton_18"))
        self.horizontalLayout_19.addWidget(self.SendButton_18)
        self.verticalLayout_5.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.itemLabelTextBrowser_19 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_19.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_19.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_19.setMinimumSize(QtCore.QSize(391, 31))
        self.itemLabelTextBrowser_19.setMaximumSize(QtCore.QSize(1234, 31))
        self.itemLabelTextBrowser_19.setObjectName(_fromUtf8("itemLabelTextBrowser_19"))
        self.horizontalLayout_20.addWidget(self.itemLabelTextBrowser_19)
        self.SendButton_19 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SendButton_19.sizePolicy().hasHeightForWidth())
        self.SendButton_19.setSizePolicy(sizePolicy)
        self.SendButton_19.setMinimumSize(QtCore.QSize(73, 32))
        self.SendButton_19.setMaximumSize(QtCore.QSize(73, 32))
        self.SendButton_19.setObjectName(_fromUtf8("SendButton_19"))
        self.horizontalLayout_20.addWidget(self.SendButton_19)
        self.verticalLayout_5.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.itemLabelTextBrowser_20 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_20.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_20.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_20.setMinimumSize(QtCore.QSize(391, 31))
        self.itemLabelTextBrowser_20.setMaximumSize(QtCore.QSize(1234, 31))
        self.itemLabelTextBrowser_20.setObjectName(_fromUtf8("itemLabelTextBrowser_20"))
        self.horizontalLayout_21.addWidget(self.itemLabelTextBrowser_20)
        self.SendButton_20 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SendButton_20.sizePolicy().hasHeightForWidth())
        self.SendButton_20.setSizePolicy(sizePolicy)
        self.SendButton_20.setMinimumSize(QtCore.QSize(73, 32))
        self.SendButton_20.setMaximumSize(QtCore.QSize(73, 32))
        self.SendButton_20.setObjectName(_fromUtf8("SendButton_20"))
        self.horizontalLayout_21.addWidget(self.SendButton_20)
        self.verticalLayout_5.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.itemLabelTextBrowser_21 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_21.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_21.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_21.setMinimumSize(QtCore.QSize(391, 31))
        self.itemLabelTextBrowser_21.setMaximumSize(QtCore.QSize(1234, 31))
        self.itemLabelTextBrowser_21.setObjectName(_fromUtf8("itemLabelTextBrowser_21"))
        self.horizontalLayout_22.addWidget(self.itemLabelTextBrowser_21)
        self.SendButton_21 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SendButton_21.sizePolicy().hasHeightForWidth())
        self.SendButton_21.setSizePolicy(sizePolicy)
        self.SendButton_21.setMinimumSize(QtCore.QSize(73, 32))
        self.SendButton_21.setMaximumSize(QtCore.QSize(73, 32))
        self.SendButton_21.setObjectName(_fromUtf8("SendButton_21"))
        self.horizontalLayout_22.addWidget(self.SendButton_21)
        self.verticalLayout_5.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.itemLabelTextBrowser_22 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_22.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_22.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_22.setMinimumSize(QtCore.QSize(391, 31))
        self.itemLabelTextBrowser_22.setMaximumSize(QtCore.QSize(1234, 31))
        self.itemLabelTextBrowser_22.setObjectName(_fromUtf8("itemLabelTextBrowser_22"))
        self.horizontalLayout_23.addWidget(self.itemLabelTextBrowser_22)
        self.SendButton_22 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SendButton_22.sizePolicy().hasHeightForWidth())
        self.SendButton_22.setSizePolicy(sizePolicy)
        self.SendButton_22.setMinimumSize(QtCore.QSize(73, 32))
        self.SendButton_22.setMaximumSize(QtCore.QSize(73, 32))
        self.SendButton_22.setObjectName(_fromUtf8("SendButton_22"))
        self.horizontalLayout_23.addWidget(self.SendButton_22)
        self.verticalLayout_5.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.itemLabelTextBrowser_23 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_23.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_23.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_23.setMinimumSize(QtCore.QSize(391, 31))
        self.itemLabelTextBrowser_23.setMaximumSize(QtCore.QSize(1234, 31))
        self.itemLabelTextBrowser_23.setObjectName(_fromUtf8("itemLabelTextBrowser_23"))
        self.horizontalLayout_24.addWidget(self.itemLabelTextBrowser_23)
        self.SendButton_23 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SendButton_23.sizePolicy().hasHeightForWidth())
        self.SendButton_23.setSizePolicy(sizePolicy)
        self.SendButton_23.setMinimumSize(QtCore.QSize(73, 32))
        self.SendButton_23.setMaximumSize(QtCore.QSize(73, 32))
        self.SendButton_23.setObjectName(_fromUtf8("SendButton_23"))
        self.horizontalLayout_24.addWidget(self.SendButton_23)
        self.verticalLayout_5.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.itemLabelTextBrowser_24 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_24.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_24.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_24.setMinimumSize(QtCore.QSize(391, 31))
        self.itemLabelTextBrowser_24.setMaximumSize(QtCore.QSize(1234, 31))
        self.itemLabelTextBrowser_24.setObjectName(_fromUtf8("itemLabelTextBrowser_24"))
        self.horizontalLayout_25.addWidget(self.itemLabelTextBrowser_24)
        self.SendButton_24 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SendButton_24.sizePolicy().hasHeightForWidth())
        self.SendButton_24.setSizePolicy(sizePolicy)
        self.SendButton_24.setMinimumSize(QtCore.QSize(73, 32))
        self.SendButton_24.setMaximumSize(QtCore.QSize(73, 32))
        self.SendButton_24.setObjectName(_fromUtf8("SendButton_24"))
        self.horizontalLayout_25.addWidget(self.SendButton_24)
        self.verticalLayout_5.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.itemLabelTextBrowser_25 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_25.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_25.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_25.setMinimumSize(QtCore.QSize(391, 31))
        self.itemLabelTextBrowser_25.setMaximumSize(QtCore.QSize(1234, 31))
        self.itemLabelTextBrowser_25.setObjectName(_fromUtf8("itemLabelTextBrowser_25"))
        self.horizontalLayout_26.addWidget(self.itemLabelTextBrowser_25)
        self.SendButton_25 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SendButton_25.sizePolicy().hasHeightForWidth())
        self.SendButton_25.setSizePolicy(sizePolicy)
        self.SendButton_25.setMinimumSize(QtCore.QSize(73, 32))
        self.SendButton_25.setMaximumSize(QtCore.QSize(73, 32))
        self.SendButton_25.setObjectName(_fromUtf8("SendButton_25"))
        self.horizontalLayout_26.addWidget(self.SendButton_25)
        self.verticalLayout_5.addLayout(self.horizontalLayout_26)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.scrollArea)

        self.retranslateUi(GenericCommandDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("clicked(QAbstractButton*)")), GenericCommandDialog.close)
        QtCore.QMetaObject.connectSlotsByName(GenericCommandDialog)

    def retranslateUi(self, GenericCommandDialog):
        GenericCommandDialog.setWindowTitle(_translate("GenericCommandDialog", "Command Page", None))
        self.subSystemCommandPageLabel.setText(_translate("GenericCommandDialog", "Subsystem", None))
        self.packetIdLabel.setText(_translate("GenericCommandDialog", "Packet ID", None))
        self.label_5.setText(_translate("GenericCommandDialog", "Send To:", None))
        self.label.setText(_translate("GenericCommandDialog", "Command", None))
        self.SendButton_1.setText(_translate("GenericCommandDialog", "Send", None))
        self.SendButton_2.setText(_translate("GenericCommandDialog", "Send", None))
        self.SendButton_3.setText(_translate("GenericCommandDialog", "Send", None))
        self.SendButton_4.setText(_translate("GenericCommandDialog", "Send", None))
        self.SendButton_5.setText(_translate("GenericCommandDialog", "Send", None))
        self.SendButton_6.setText(_translate("GenericCommandDialog", "Send", None))
        self.SendButton_7.setText(_translate("GenericCommandDialog", "Send", None))
        self.SendButton_8.setText(_translate("GenericCommandDialog", "Send", None))
        self.SendButton_9.setText(_translate("GenericCommandDialog", "Send", None))
        self.SendButton_10.setText(_translate("GenericCommandDialog", "Send", None))
        self.SendButton_11.setText(_translate("GenericCommandDialog", "Send", None))
        self.SendButton_12.setText(_translate("GenericCommandDialog", "Send", None))
        self.SendButton_13.setText(_translate("GenericCommandDialog", "Send", None))
        self.SendButton_14.setText(_translate("GenericCommandDialog", "Send", None))
        self.SendButton_15.setText(_translate("GenericCommandDialog", "Send", None))
        self.SendButton_16.setText(_translate("GenericCommandDialog", "Send", None))
        self.SendButton_17.setText(_translate("GenericCommandDialog", "Send", None))
        self.SendButton_18.setText(_translate("GenericCommandDialog", "Send", None))
        self.SendButton_19.setText(_translate("GenericCommandDialog", "Send", None))
        self.SendButton_20.setText(_translate("GenericCommandDialog", "Send", None))
        self.SendButton_21.setText(_translate("GenericCommandDialog", "Send", None))
        self.SendButton_22.setText(_translate("GenericCommandDialog", "Send", None))
        self.SendButton_23.setText(_translate("GenericCommandDialog", "Send", None))
        self.SendButton_24.setText(_translate("GenericCommandDialog", "Send", None))
        self.SendButton_25.setText(_translate("GenericCommandDialog", "Send", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    GenericCommandDialog = QtGui.QWidget()
    ui = Ui_GenericCommandDialog()
    ui.setupUi(GenericCommandDialog)
    GenericCommandDialog.show()
    sys.exit(app.exec_())

