# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ParameterDialog.ui'
#
# Created: Wed Mar 25 12:38:59 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setEnabled(True)
        Dialog.resize(786, 466)
        self.label_title = QtGui.QLabel(Dialog)
        self.label_title.setGeometry(QtCore.QRect(330, 70, 91, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(10)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName(_fromUtf8("label_title"))
        self.label_instructions = QtGui.QLabel(Dialog)
        self.label_instructions.setGeometry(QtCore.QRect(120, 90, 551, 31))
        self.label_instructions.setAlignment(QtCore.Qt.AlignCenter)
        self.label_instructions.setObjectName(_fromUtf8("label_instructions"))
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(670, 430, 101, 31))
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.status_box = QtGui.QTextBrowser(Dialog)
        self.status_box.setGeometry(QtCore.QRect(480, 30, 201, 41))
        self.status_box.setAutoFillBackground(False)
        self.status_box.setObjectName(_fromUtf8("status_box"))
        self.label_param_title_2 = QtGui.QLabel(Dialog)
        self.label_param_title_2.setGeometry(QtCore.QRect(480, 10, 51, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(10)
        self.label_param_title_2.setFont(font)
        self.label_param_title_2.setObjectName(_fromUtf8("label_param_title_2"))
        self.SendButton_1 = QtGui.QPushButton(Dialog)
        self.SendButton_1.setGeometry(QtCore.QRect(690, 40, 71, 27))
        self.SendButton_1.setObjectName(_fromUtf8("SendButton_1"))
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(260, 10, 81, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.subSystemCommandPageLabel = QtGui.QLabel(Dialog)
        self.subSystemCommandPageLabel.setGeometry(QtCore.QRect(30, 10, 91, 17))
        self.subSystemCommandPageLabel.setObjectName(_fromUtf8("subSystemCommandPageLabel"))
        self.subSystemTextBrowser = QtGui.QTextBrowser(Dialog)
        self.subSystemTextBrowser.setGeometry(QtCore.QRect(30, 30, 221, 41))
        self.subSystemTextBrowser.setObjectName(_fromUtf8("subSystemTextBrowser"))
        self.commandAddressTextBrowser = QtGui.QTextBrowser(Dialog)
        self.commandAddressTextBrowser.setGeometry(QtCore.QRect(260, 30, 211, 41))
        self.commandAddressTextBrowser.setObjectName(_fromUtf8("commandAddressTextBrowser"))
        self.scrollArea_2 = QtGui.QScrollArea(Dialog)
        self.scrollArea_2.setGeometry(QtCore.QRect(20, 120, 741, 301))
        self.scrollArea_2.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea_2.setBaseSize(QtCore.QSize(0, 500))
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 724, 1000))
        self.scrollAreaWidgetContents_2.setMinimumSize(QtCore.QSize(0, 1000))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.input_2 = QtGui.QTextEdit(self.scrollAreaWidgetContents_2)
        self.input_2.setGeometry(QtCore.QRect(440, 80, 271, 41))
        self.input_2.setObjectName(_fromUtf8("input_2"))
        self.descrip_1 = QtGui.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.descrip_1.setGeometry(QtCore.QRect(150, 30, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.descrip_1.setFont(font)
        self.descrip_1.setObjectName(_fromUtf8("descrip_1"))
        self.label_input_title_2 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_input_title_2.setGeometry(QtCore.QRect(440, 10, 91, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(10)
        self.label_input_title_2.setFont(font)
        self.label_input_title_2.setObjectName(_fromUtf8("label_input_title_2"))
        self.input_5 = QtGui.QTextEdit(self.scrollAreaWidgetContents_2)
        self.input_5.setGeometry(QtCore.QRect(440, 230, 271, 41))
        self.input_5.setObjectName(_fromUtf8("input_5"))
        self.label_param_title_3 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_param_title_3.setGeometry(QtCore.QRect(10, 10, 111, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(10)
        self.label_param_title_3.setFont(font)
        self.label_param_title_3.setObjectName(_fromUtf8("label_param_title_3"))
        self.label_descrip_2 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_descrip_2.setGeometry(QtCore.QRect(150, 10, 111, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(10)
        self.label_descrip_2.setFont(font)
        self.label_descrip_2.setObjectName(_fromUtf8("label_descrip_2"))
        self.input_1 = QtGui.QTextEdit(self.scrollAreaWidgetContents_2)
        self.input_1.setGeometry(QtCore.QRect(440, 30, 271, 41))
        self.input_1.setObjectName(_fromUtf8("input_1"))
        self.paramName_1 = QtGui.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.paramName_1.setGeometry(QtCore.QRect(10, 30, 131, 41))
        self.paramName_1.setObjectName(_fromUtf8("paramName_1"))
        self.input_3 = QtGui.QTextEdit(self.scrollAreaWidgetContents_2)
        self.input_3.setGeometry(QtCore.QRect(440, 130, 271, 41))
        self.input_3.setObjectName(_fromUtf8("input_3"))
        self.input_4 = QtGui.QTextEdit(self.scrollAreaWidgetContents_2)
        self.input_4.setGeometry(QtCore.QRect(440, 180, 271, 41))
        self.input_4.setObjectName(_fromUtf8("input_4"))
        self.input_6 = QtGui.QTextEdit(self.scrollAreaWidgetContents_2)
        self.input_6.setGeometry(QtCore.QRect(440, 280, 271, 41))
        self.input_6.setObjectName(_fromUtf8("input_6"))
        self.input_7 = QtGui.QTextEdit(self.scrollAreaWidgetContents_2)
        self.input_7.setGeometry(QtCore.QRect(440, 330, 271, 41))
        self.input_7.setObjectName(_fromUtf8("input_7"))
        self.input_8 = QtGui.QTextEdit(self.scrollAreaWidgetContents_2)
        self.input_8.setGeometry(QtCore.QRect(440, 380, 271, 41))
        self.input_8.setObjectName(_fromUtf8("input_8"))
        self.input_9 = QtGui.QTextEdit(self.scrollAreaWidgetContents_2)
        self.input_9.setGeometry(QtCore.QRect(440, 430, 271, 41))
        self.input_9.setObjectName(_fromUtf8("input_9"))
        self.paramName_2 = QtGui.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.paramName_2.setGeometry(QtCore.QRect(10, 80, 131, 41))
        self.paramName_2.setObjectName(_fromUtf8("paramName_2"))
        self.descrip_2 = QtGui.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.descrip_2.setGeometry(QtCore.QRect(150, 80, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.descrip_2.setFont(font)
        self.descrip_2.setObjectName(_fromUtf8("descrip_2"))
        self.descrip_3 = QtGui.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.descrip_3.setGeometry(QtCore.QRect(150, 130, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.descrip_3.setFont(font)
        self.descrip_3.setObjectName(_fromUtf8("descrip_3"))
        self.paramName_3 = QtGui.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.paramName_3.setGeometry(QtCore.QRect(10, 130, 131, 41))
        self.paramName_3.setObjectName(_fromUtf8("paramName_3"))
        self.paramName_4 = QtGui.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.paramName_4.setGeometry(QtCore.QRect(10, 180, 131, 41))
        self.paramName_4.setObjectName(_fromUtf8("paramName_4"))
        self.descrip_4 = QtGui.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.descrip_4.setGeometry(QtCore.QRect(150, 180, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.descrip_4.setFont(font)
        self.descrip_4.setObjectName(_fromUtf8("descrip_4"))
        self.descrip_5 = QtGui.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.descrip_5.setGeometry(QtCore.QRect(150, 230, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.descrip_5.setFont(font)
        self.descrip_5.setObjectName(_fromUtf8("descrip_5"))
        self.paramName_5 = QtGui.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.paramName_5.setGeometry(QtCore.QRect(10, 230, 131, 41))
        self.paramName_5.setObjectName(_fromUtf8("paramName_5"))
        self.descrip_6 = QtGui.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.descrip_6.setGeometry(QtCore.QRect(150, 280, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.descrip_6.setFont(font)
        self.descrip_6.setObjectName(_fromUtf8("descrip_6"))
        self.paramName_6 = QtGui.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.paramName_6.setGeometry(QtCore.QRect(10, 280, 131, 41))
        self.paramName_6.setObjectName(_fromUtf8("paramName_6"))
        self.descrip_7 = QtGui.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.descrip_7.setGeometry(QtCore.QRect(150, 330, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.descrip_7.setFont(font)
        self.descrip_7.setObjectName(_fromUtf8("descrip_7"))
        self.paramName_7 = QtGui.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.paramName_7.setGeometry(QtCore.QRect(10, 330, 131, 41))
        self.paramName_7.setObjectName(_fromUtf8("paramName_7"))
        self.paramName_8 = QtGui.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.paramName_8.setGeometry(QtCore.QRect(10, 380, 131, 41))
        self.paramName_8.setObjectName(_fromUtf8("paramName_8"))
        self.descrip_8 = QtGui.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.descrip_8.setGeometry(QtCore.QRect(150, 380, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.descrip_8.setFont(font)
        self.descrip_8.setObjectName(_fromUtf8("descrip_8"))
        self.paramName_9 = QtGui.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.paramName_9.setGeometry(QtCore.QRect(10, 430, 131, 41))
        self.paramName_9.setObjectName(_fromUtf8("paramName_9"))
        self.descrip_9 = QtGui.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.descrip_9.setGeometry(QtCore.QRect(150, 430, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.descrip_9.setFont(font)
        self.descrip_9.setObjectName(_fromUtf8("descrip_9"))
        self.descrip_10 = QtGui.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.descrip_10.setGeometry(QtCore.QRect(150, 480, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.descrip_10.setFont(font)
        self.descrip_10.setObjectName(_fromUtf8("descrip_10"))
        self.paramName_10 = QtGui.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.paramName_10.setGeometry(QtCore.QRect(10, 480, 131, 41))
        self.paramName_10.setObjectName(_fromUtf8("paramName_10"))
        self.input_10 = QtGui.QTextEdit(self.scrollAreaWidgetContents_2)
        self.input_10.setGeometry(QtCore.QRect(440, 480, 271, 41))
        self.input_10.setObjectName(_fromUtf8("input_10"))
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("clicked(QAbstractButton*)")), Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label_title.setText(_translate("Dialog", "Parameters", None))
        self.label_instructions.setText(_translate("Dialog", "Please enter the following parameters then click \'Send\':", None))
        self.label_param_title_2.setText(_translate("Dialog", "Status:", None))
        self.SendButton_1.setText(_translate("Dialog", "Send", None))
        self.label_5.setText(_translate("Dialog", "Command:", None))
        self.subSystemCommandPageLabel.setText(_translate("Dialog", "Subsystem:", None))
        self.label_input_title_2.setText(_translate("Dialog", "Input", None))
        self.label_param_title_3.setText(_translate("Dialog", "Parameter", None))
        self.label_descrip_2.setText(_translate("Dialog", "Description", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

