# Rule for traditional CFE table generation via elf2cfetbl

# The dependency of this target should always be an absolute pathname to
# the intermediate library file as it is generated by a CMake script via
# the TARGET_FILE property.  Therefore, the same path should still work
# after the "cd" command.  The "cd" is so the ar tool writes the object file
# into a separate dir, in case of similarly-named files on different cpus.
elf/%:
	@mkdir -pv "$(dir $(@))"
	cd "$(dir $(@))" && $(AR) x "$(<)" "$(notdir $(@))"
