name: "Internal Code Coverage Analysis"

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:
  schedule:
    # 11:00 PM UTC every Sunday
    - cron:  '0 23 * * 0'

env:
  SIMULATION: native
  ENABLE_UNIT_TESTS: true
  OMIT_DEPRECATED: false
  BUILDTYPE: debug

jobs:

  Execute-Unit-Tests:
    name: Build and Execute CFE unit tests
    runs-on: cfs-self-hosted
    container:
      image: aetd-dockerlab.gsfc.nasa.gov/gsfc-cfs/github-actions-ci-cd/cfsbuildenv-ubuntu22
    timeout-minutes: 15

    steps:
      - name: Checkout CFE
        uses: actions/checkout@v4
        with:
          path: cfe

      - name: Set up Dependencies
        uses: ./cfe/.github/actions/setup-cfe
        with:
          source-dir: .
          preferred-ref: ${{ github.head_ref }}

      # Setup the build system
      - name: Set up for build
        run: make prep

      # Setup the build system
      - name: Build dependencies
        run: make -C build mission-prebuild

      # Build the CFE core modules
      - name: Build CFE core modules
        run: |
          make -C build/native/default_cpu1/config
          make -C build/native/default_cpu1/core_api
          make -C build/native/default_cpu1/core_private
          make -C build/native/default_cpu1/es
          make -C build/native/default_cpu1/evs
          make -C build/native/default_cpu1/fs
          make -C build/native/default_cpu1/msg
          make -C build/native/default_cpu1/resourceid
          make -C build/native/default_cpu1/sb
          make -C build/native/default_cpu1/sbr
          make -C build/native/default_cpu1/tbl
          make -C build/native/default_cpu1/time

      # Initialize lcov and test the code
      - name: Execute Unit Tests
        run: |
          lcov --capture --initial --directory build --output-file coverage_base.info
          (cd build/native/default_cpu1/config && ctest --output-on-failure)
          (cd build/native/default_cpu1/core_api && ctest --output-on-failure)
          (cd build/native/default_cpu1/core_private && ctest --output-on-failure)
          (cd build/native/default_cpu1/es && ctest --output-on-failure)
          (cd build/native/default_cpu1/evs && ctest --output-on-failure)
          (cd build/native/default_cpu1/fs && ctest --output-on-failure)
          (cd build/native/default_cpu1/msg && ctest --output-on-failure)
          (cd build/native/default_cpu1/resourceid && ctest --output-on-failure)
          (cd build/native/default_cpu1/sb && ctest --output-on-failure)
          (cd build/native/default_cpu1/sbr && ctest --output-on-failure)
          (cd build/native/default_cpu1/tbl && ctest --output-on-failure)
          (cd build/native/default_cpu1/time && ctest --output-on-failure)

      - name: Calculate Coverage
        run: |
          lcov --capture --rc lcov_branch_coverage=1 --directory build --output-file coverage_test.info
          lcov --rc lcov_branch_coverage=1 --add-tracefile coverage_base.info --add-tracefile coverage_test.info --output-file coverage_total.info
          genhtml coverage_total.info --branch-coverage --output-directory lcov | tee lcov_out.txt

      - name: Confirm Minimum Coverage
        run: |
          missed_branches=39
          missed_lines=19
          branch_nums=$(grep -A 3 "Overall coverage rate" lcov_out.txt | grep branches | grep -oP "[0-9]+[0-9]*")
          line_nums=$(grep -A 3 "Overall coverage rate" lcov_out.txt | grep lines | grep -oP "[0-9]+[0-9]*")

          branch_diff=$(echo $branch_nums | awk '{ print $4 - $3 }')
          line_diff=$(echo $line_nums | awk '{ print $4 - $3 }')
          if [ $branch_diff -gt $missed_branches ] || [ $line_diff -gt $missed_lines ]
          then
            grep -A 3 "Overall coverage rate" lcov_out.txt
            echo "$branch_diff branches missed, $missed_branches allowed"
            echo "$line_diff lines missed, $missed_lines allowed"
            exit -1
          fi
