name: "Code Coverage Analysis"

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:
  schedule:
    # 11:00 PM UTC every Sunday
    - cron:  '0 23 * * 0'

env:
  SIMULATION: native
  ENABLE_UNIT_TESTS: true
  OMIT_DEPRECATED: false
  BUILDTYPE: debug

jobs:
 Execute-Unit-Tests:
    name: Build and Execute CFE unit tests
    runs-on: ubuntu-22.04
    container: ghcr.io/core-flight-system/cfsbuildenv-linux:latest
    timeout-minutes: 15

    steps:
      - name: Install coverage tools
        run: sudo apt-get install lcov -y

      - name: Checkout cFE
        uses: actions/checkout@v4
        with:
          path: cfe

      - name: Set up Dependencies
        uses: ./cfe/.github/actions/setup-cfe
        with:
          source-dir: .
          preferred-ref: ${{ github.head_ref }}
          org: 'nasa'

      - name: Execute coverage testing
        uses: ./cfe/.github/actions/code-coverage
        with:
          module-list: config core_api core_private es evs fs msg resourceid sb sbr tbl time
          allowed-missed-branches: 14
          allowed-missed-lines: 8
          allowed-missed-functions: 0