name: "Functional Test"

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    # 11:45 PM UTC every Sunday
    - cron:  '45 23 * * 0'

env:
  SIMULATION: native
  ENABLE_UNIT_TESTS: true
  OMIT_DEPRECATED: true
  BUILDTYPE: release

jobs:

  #Check for duplicate actions. Skips push actions if there is a matching or duplicate pull-request action.
  check-for-duplicates:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content'
          skip_after_successful_duplicate: 'true'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  Local-Test-Build:
    name: Build cFE
    #Continue if check-for-duplicates found no duplicates. Always runs for pull-requests.
    needs: check-for-duplicates
    if: ${{ needs.check-for-duplicates.outputs.should_skip != 'true' }}
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    steps:
      - name: Checkout cFE
        uses: actions/checkout@v4
        with:
          path: cfe

      - name: Set up Dependencies
        uses: ./cfe/.github/actions/setup-cfe-opensource
        with:
          source-dir: .
          preferred-ref: ${{ github.head_ref }}

      # Setup the build system
      - name: Set up for build
        run: make prep

      - name: Build CFE
        run: make install

      - name: Generate Startup Link
        run: ln -s core-cpu1 ./build/exe/cpu1/container-start

      - name: List cpu1
        run: ls build/exe/cpu1/

      - name: Archive binaries
        run: |
          cd $GITHUB_WORKSPACE/build/exe
          find -maxdepth 1 -mindepth 1 -type d | while read dir
          do
            inst=$(basename ${dir})
            tar Jcv -f $GITHUB_WORKSPACE/${inst}-bin.tar.xz -C ${inst} .
          done

      - name: Upload all artifacts
        uses: actions/upload-artifact@v4
        with:
            name: functional-test-bin
            path: ./*.tar.xz
