name: Internal MCDC Analysis

on:
  push:
  pull_request:

# Force bash to apply pipefail option so pipeline failures aren't masked
defaults:
  run:
    shell: bash
    
env:
  SIMULATION: native
  ENABLE_UNIT_TESTS: true
  OMIT_DEPRECATED: true
  BUILDTYPE: debug
  TESTS_RAN: false
  
jobs:
  # Checks for duplicate actions. Skips push actions if there is a matching or
  # duplicate pull-request action.
  checks-for-duplicates:
    runs-on: Linux
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: synced-actions/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content'
          skip_after_successful_duplicate: 'true'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  mcdc:
    needs: checks-for-duplicates
    if: ${{ needs.checks-for-duplicates.outputs.should_skip != 'true' || contains(github.ref, 'main') }}
    name: Build and Run MCDC
    runs-on: Linux
    container: ghcr.io/core-flight-system/mcdc:latest

    steps:                  
      - name: Checkout Bundle Main
        uses: actions/checkout@v4
        with:
          submodules: false
          repository: cFS/cFS

      - name: Checkout cFE
        uses: actions/checkout@v4        
        with:
          path: cfe

      - name: Get cFS submodules
        run: |
          git submodule sync
          git submodule update --init --recursive

      - name: Checkout MCDC Script
        uses: actions/checkout@v4
        with:
          repository: cFS/workflows
          path: workflows

      - name: Modify osal to include coverage flags
        run: |
          sed -i 's/target_compile_options.*)/target_compile_options(ut_coverage_compile INTERFACE -pg -O0 -fprofile-arcs -ftest-coverage -fcondition-coverage -fprofile-abs-path)/' osal/src/bsp/generic-linux/CMakeLists.txt       
          sed -i 's/set(UT_COVERAGE_COMPILE_FLAGS.*)/set(UT_COVERAGE_COMPILE_FLAGS -pg --coverage -O0 -fcondition-coverage -fprofile-abs-path)/' osal/src/bsp/generic-linux/build_options.cmake
          sed -i 's/set(UT_COVERAGE_LINK_FLAGS.*)/set(UT_COVERAGE_LINK_FLAGS -pg --coverage -O0 -fcondition-coverage -fprofile-abs-path)/' osal/src/bsp/generic-linux/build_options.cmake

      - name: Set up for build
        run: |
          cp ./cfe/cmake/Makefile.sample Makefile
          cp -r ./cfe/cmake/sample_defs sample_defs
          make prep
          make -C build mission-prebuild

      - name: Build
        run: |
          make -C build/native/default_cpu1/config
          make -C build/native/default_cpu1/core_api
          make -C build/native/default_cpu1/core_private
          make -C build/native/default_cpu1/es
          make -C build/native/default_cpu1/evs
          make -C build/native/default_cpu1/fs
          make -C build/native/default_cpu1/msg
          make -C build/native/default_cpu1/resourceid
          make -C build/native/default_cpu1/sb
          make -C build/native/default_cpu1/sbr
          make -C build/native/default_cpu1/tbl
          make -C build/native/default_cpu1/time

      - name: Test
        run: |
          (cd build/native/default_cpu1/config && ctest --output-on-failure || true) | tee -a test_results.txt
          (cd build/native/default_cpu1/core_api && ctest --output-on-failure || true) | tee -a test_results.txt
          (cd build/native/default_cpu1/core_private && ctest --output-on-failure || true) | tee -a test_results.txt
          (cd build/native/default_cpu1/es && ctest --output-on-failure || true) | tee -a test_results.txt
          (cd build/native/default_cpu1/evs && ctest --output-on-failure || true) | tee -a test_results.txt
          (cd build/native/default_cpu1/fs && ctest --output-on-failure || true) | tee -a test_results.txt
          (cd build/native/default_cpu1/msg && ctest --output-on-failure || true) | tee -a test_results.txt
          (cd build/native/default_cpu1/resourceid && ctest --output-on-failure || true) | tee -a test_results.txt
          (cd build/native/default_cpu1/sb && ctest --output-on-failure || true) | tee -a test_results.txt
          (cd build/native/default_cpu1/sbr && ctest --output-on-failure || true) | tee -a test_results.txt
          (cd build/native/default_cpu1/tbl && ctest --output-on-failure || true) | tee -a test_results.txt
          (cd build/native/default_cpu1/time && ctest --output-on-failure || true) | tee -a test_results.txt
          echo "TESTS_RAN=true" >> $GITHUB_ENV

      - name: Grab test modules
        if: ${{ env.TESTS_RAN == 'true' }}
        run: |
          echo "MODULES=$(grep -oP 'Test\s+#\d+: \K[\w\-\_]+(?= )' test_results.txt | tr '\n' ' ' | sed 's/ $//')" >> $GITHUB_ENV

      - name: Run mcdc analysis
        if: ${{ env.TESTS_RAN == 'true' }}
        run: bash workflows/.github/scripts/mcdc-analyze.sh
        
      - name: Archive unit test results
        # Upload if success or failure which supports skipping, unlike always()
        if: ${{ env.TESTS_RAN == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: Unit test results
          path: |
            test_results.txt
      
      - name: Archive mcdc results
        # Upload if success or failure which supports skipping, unlike always()
        if: ${{ env.TESTS_RAN == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: MCDC results
          path: |
            **/*.gcov
            mcdc_results.txt