name: Static Analysis

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:
  schedule:
    # 11:59 PM UTC every Sunday
    - cron:  '59 23 * * 0'

jobs:
  static-analysis:
    name: Run Static Analysis
    runs-on: cfs-self-hosted
    container:
      image: aetd-dockerlab.gsfc.nasa.gov/gsfc-cfs/github-actions-ci-cd/cfsbuildenv-ubuntu22
    timeout-minutes: 15

    steps:
      - name: Checkout CFE
        uses: actions/checkout@v4
        with:
          path: cfe

      - name: Set up Dependencies
        uses: ./cfe/.github/actions/setup-cfe
        with:
          source-dir: .
          preferred-ref: ${{ github.head_ref }}

      # Setup the build system
      - name: Create build tree
        run: cmake -DCMAKE_INSTALL_PREFIX=/exe -DCMAKE_BUILD_TYPE=debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DSIMULATION=native -S cfe -B build

      - name: List Files
        run: ls -la build/native/*

      - name: Run cppcheck
        uses: cFS/workflows/actions/cppcheck@dev
        id: run-cppcheck
        with:
          strict-dir-list: './cfe/modules/core_api/fsw ./cfe/modules/core_private/fsw ./cfe/modules/es/fsw ./cfe/modules/evs/fsw ./cfe/modules/fs/fsw ./cfe/modules/msg/fsw ./cfe/modules/resourceid/fsw ./cfe/modules/sb/fsw ./modules/cfe/sbr/fsw ./modules/cfe/tbl/fsw ./cfe/modules/time/fsw -UCFE_PLATFORM_TIME_CFG_CLIENT -DCFE_PLATFORM_TIME_CFG_SERVER'
          compile-commands-json: ./build/compile_commands.json ./build/native/default_cpu1/compile_commands.json
          module-path: cfe
